<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 환자-수준 예측 | The Book of OHDSI Korea</title>
  <meta name="description" content="A book about the Observational Health Data Sciences and Informatics (OHDSI). It described the OHDSI community, open standards and open source software." />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 환자-수준 예측 | The Book of OHDSI Korea" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ohdsi-korea.github.io/TheBookOfOhdsiKorea/" />
  <meta property="og:image" content="https://ohdsi-korea.github.io/TheBookOfOhdsiKorea/images/Cover/Cover.png" />
  <meta property="og:description" content="A book about the Observational Health Data Sciences and Informatics (OHDSI). It described the OHDSI community, open standards and open source software." />
  <meta name="github-repo" content="OHDSI-Korea/TheBookOfOhdsiKorea" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 환자-수준 예측 | The Book of OHDSI Korea" />
  
  <meta name="twitter:description" content="A book about the Observational Health Data Sciences and Informatics (OHDSI). It described the OHDSI community, open standards and open source software." />
  <meta name="twitter:image" content="https://ohdsi-korea.github.io/TheBookOfOhdsiKorea/images/Cover/Cover.png" />

<meta name="author" content="OHDSI-Korea" />


<meta name="date" content="2019-10-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="PopulationLevelEstimation.html">
<link rel="next" href="EvidenceQuality.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104086677-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104086677-2');
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Book of OHDSI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>서문</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i>이 책의 목표</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i>이 책의 구성</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#eab8b0ec97acec9e90"><i class="fa fa-check"></i>기여자</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i>소프트웨어 버전</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#eb9dbcec9db4ec84a0ec8aa4"><i class="fa fa-check"></i>라이선스</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i>이 책이 쓰여진 과정</a></li>
</ul></li>
<li class="part"><span><b>I The OHDSI Community</b></span></li>
<li class="chapter" data-level="1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html"><i class="fa fa-check"></i><b>1</b> The OHDSI Community</a><ul>
<li class="chapter" data-level="1.1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#---the-journey-from-data-to-evidence"><i class="fa fa-check"></i><b>1.1</b> 데이터에서 근거로의 여정 (The Journey from Data to Evidence)</a></li>
<li class="chapter" data-level="1.2" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#-observational-medical-outcomes-partnership-omop"><i class="fa fa-check"></i><b>1.2</b> 오몹 (Observational Medical Outcomes Partnership, OMOP)</a></li>
<li class="chapter" data-level="1.3" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#----ohdsi-as-an-open-science-collaborative"><i class="fa fa-check"></i><b>1.3</b> 개방형 협업 공동체로서의 오딧세이 (OHDSI as an Open-Science Collaborative)</a><ul>
<li class="chapter" data-level="1.3.1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsi--our-mission"><i class="fa fa-check"></i><b>1.3.1</b> OHDSI의 사명 (Our Mission)</a></li>
<li class="chapter" data-level="1.3.2" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsi--our-vision"><i class="fa fa-check"></i><b>1.3.2</b> OHDSI의 이상 (Our Vision)</a></li>
<li class="chapter" data-level="1.3.3" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsi---our-objectives"><i class="fa fa-check"></i><b>1.3.3</b> OHDSI의 핵심 가치 (Our Objectives)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#--ohdsis-progress"><i class="fa fa-check"></i><b>1.4</b> 오딧세이의 진척 (OHDSI’s Progress)</a></li>
<li class="chapter" data-level="1.5" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#collaborating-in-ohdsi"><i class="fa fa-check"></i><b>1.5</b> Collaborating in OHDSI</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>1.6</b> 한국 오딧세이의 역사</a></li>
<li class="chapter" data-level="1.7" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#section-1.7"><i class="fa fa-check"></i><b>1.7</b> 요약</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="WhereToBegin.html"><a href="WhereToBegin.html"><i class="fa fa-check"></i><b>2</b> 어디서부터 시작할 것인가 (Where to Begin)</a><ul>
<li class="chapter" data-level="2.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>2.1</b> 여정에 동참하십시오</a><ul>
<li class="chapter" data-level="2.1.1" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi-"><i class="fa fa-check"></i><b>2.1.1</b> OHDSI 포럼</a></li>
<li class="chapter" data-level="2.1.2" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi-"><i class="fa fa-check"></i><b>2.1.2</b> OHDSI 이벤트</a></li>
<li class="chapter" data-level="2.1.3" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi--"><i class="fa fa-check"></i><b>2.1.3</b> OHDSI 커뮤니티 콜</a></li>
<li class="chapter" data-level="2.1.4" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi-"><i class="fa fa-check"></i><b>2.1.4</b> OHDSI 워크그룹</a></li>
<li class="chapter" data-level="2.1.5" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi--"><i class="fa fa-check"></i><b>2.1.5</b> OHDSI 지역 지부</a></li>
<li class="chapter" data-level="2.1.6" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi--"><i class="fa fa-check"></i><b>2.1.6</b> OHDSI 리서치 네트워크</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>2.2</b> 적합한 위치</a></li>
<li class="chapter" data-level="2.3" data-path="WhereToBegin.html"><a href="WhereToBegin.html#-1"><i class="fa fa-check"></i><b>2.3</b> 요약</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="OpenScience.html"><a href="OpenScience.html"><i class="fa fa-check"></i><b>3</b> 오픈 사이언스</a><ul>
<li class="chapter" data-level="3.1" data-path="OpenScience.html"><a href="OpenScience.html#--open-science"><i class="fa fa-check"></i><b>3.1</b> 오픈 사이언스 (Open Science)</a></li>
<li class="chapter" data-level="3.2" data-path="OpenScience.html"><a href="OpenScience.html#---study-a-thon"><i class="fa fa-check"></i><b>3.2</b> 실천의 오픈 사이언스: Study-a-Thon</a></li>
<li class="chapter" data-level="3.3" data-path="OpenScience.html"><a href="OpenScience.html#--open-standard"><i class="fa fa-check"></i><b>3.3</b> 오픈 스탠다드 (Open Standard)</a></li>
<li class="chapter" data-level="3.4" data-path="OpenScience.html"><a href="OpenScience.html#--open-source"><i class="fa fa-check"></i><b>3.4</b> 오픈 소스 (Open Source)</a></li>
<li class="chapter" data-level="3.5" data-path="OpenScience.html"><a href="OpenScience.html#--open-data"><i class="fa fa-check"></i><b>3.5</b> 오픈 데이터 (Open Data)</a></li>
<li class="chapter" data-level="3.6" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>3.6</b> 열린 담론</a></li>
<li class="chapter" data-level="3.7" data-path="OpenScience.html"><a href="OpenScience.html#ohdsi-fair--"><i class="fa fa-check"></i><b>3.7</b> OHDSI와 FAIR 가이드 원칙</a><ul>
<li class="chapter" data-level="3.7.1" data-path="OpenScience.html"><a href="OpenScience.html#section-3.7.1"><i class="fa fa-check"></i><b>3.7.1</b> 도입</a></li>
<li class="chapter" data-level="3.7.2" data-path="OpenScience.html"><a href="OpenScience.html#section-3.7.2"><i class="fa fa-check"></i><b>3.7.2</b> 검색성</a></li>
<li class="chapter" data-level="3.7.3" data-path="OpenScience.html"><a href="OpenScience.html#section-3.7.3"><i class="fa fa-check"></i><b>3.7.3</b> 접근성</a></li>
<li class="chapter" data-level="3.7.4" data-path="OpenScience.html"><a href="OpenScience.html#section-3.7.4"><i class="fa fa-check"></i><b>3.7.4</b> 상호운용성</a></li>
<li class="chapter" data-level="3.7.5" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>3.7.5</b> 재사용 가능성</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Uniform Data Representation</b></span></li>
<li class="chapter" data-level="4" data-path="CommonDataModel.html"><a href="CommonDataModel.html"><i class="fa fa-check"></i><b>4</b> 공통 데이터 모델</a><ul>
<li class="chapter" data-level="4.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>4.1</b> 설계 원리</a></li>
<li class="chapter" data-level="4.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>4.2</b> 데이터 모델 규칙</a><ul>
<li class="chapter" data-level="4.2.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#model-Conv"><i class="fa fa-check"></i><b>4.2.1</b> 모델의 일반적인 규칙</a></li>
<li class="chapter" data-level="4.2.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>4.2.2</b> 스키마의 일반적인 규칙</a></li>
<li class="chapter" data-level="4.2.3" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>4.2.3</b> 데이터 테이블의 일반적인 규칙</a></li>
<li class="chapter" data-level="4.2.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#domains"><i class="fa fa-check"></i><b>4.2.4</b> 도메인의 일반적인 규칙</a></li>
<li class="chapter" data-level="4.2.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#concept---"><i class="fa fa-check"></i><b>4.2.5</b> Concept을 통한 내용의 표현</a></li>
<li class="chapter" data-level="4.2.6" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>4.2.6</b> 필드 명명 규칙</a></li>
<li class="chapter" data-level="4.2.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#concepts-Sources"><i class="fa fa-check"></i><b>4.2.7</b> concept과 원본 값과의 차이</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#-cdm-"><i class="fa fa-check"></i><b>4.3</b> 표준화된 CDM 테이블</a><ul>
<li class="chapter" data-level="4.3.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>4.3.1</b> 실행 예제: 자궁내막증</a></li>
<li class="chapter" data-level="4.3.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#person"><i class="fa fa-check"></i><b>4.3.2</b> PERSON 테이블</a></li>
<li class="chapter" data-level="4.3.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#observationPeriod"><i class="fa fa-check"></i><b>4.3.3</b> OBSERVATION_PERIOD 테이블</a></li>
<li class="chapter" data-level="4.3.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#visitOccurrence"><i class="fa fa-check"></i><b>4.3.4</b> VISIT_OCCURRENCE</a></li>
<li class="chapter" data-level="4.3.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#conditionOccurrence"><i class="fa fa-check"></i><b>4.3.5</b> CONDITION_OCCURRENCE</a></li>
<li class="chapter" data-level="4.3.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#drugExposure"><i class="fa fa-check"></i><b>4.3.6</b> DRUG_EXPOSURE</a></li>
<li class="chapter" data-level="4.3.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#procedureOccurrence"><i class="fa fa-check"></i><b>4.3.7</b> PROCEDURE_OCCURRENCE</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>4.4</b> 부가 정보</a></li>
<li class="chapter" data-level="4.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#-2"><i class="fa fa-check"></i><b>4.5</b> 요약</a></li>
<li class="chapter" data-level="4.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#section-4.6"><i class="fa fa-check"></i><b>4.6</b> 예제</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html"><i class="fa fa-check"></i><b>5</b> 표준화된 용어</a><ul>
<li class="chapter" data-level="5.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#-vocabularies----"><i class="fa fa-check"></i><b>5.1</b> 왜 용어(Vocabularies) 인가, 그리고 왜 표준화인가?</a><ul>
<li class="chapter" data-level="5.1.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>5.1.1</b> 표준화된 용어 구축</a></li>
<li class="chapter" data-level="5.1.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#accessVocabularies"><i class="fa fa-check"></i><b>5.1.2</b> 표준화된 용어 이용하기</a></li>
<li class="chapter" data-level="5.1.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#---vs-"><i class="fa fa-check"></i><b>5.1.3</b> 용어의 원천 : 도입 vs 구축</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#section-5.2"><i class="fa fa-check"></i><b>5.2</b> 개념</a><ul>
<li class="chapter" data-level="5.2.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#-id-concept-ids"><i class="fa fa-check"></i><b>5.2.1</b> 개념 ID (Concept IDs)</a></li>
<li class="chapter" data-level="5.2.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#--concept-names"><i class="fa fa-check"></i><b>5.2.2</b> 개념 이름 (Concept Names)</a></li>
<li class="chapter" data-level="5.2.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptDomains"><i class="fa fa-check"></i><b>5.2.3</b> 도메인</a></li>
<li class="chapter" data-level="5.2.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#-vocabularies"><i class="fa fa-check"></i><b>5.2.4</b> 용어 (Vocabularies)</a></li>
<li class="chapter" data-level="5.2.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#--concept-classes"><i class="fa fa-check"></i><b>5.2.5</b> 개념 계층 (Concept Classes)</a></li>
<li class="chapter" data-level="5.2.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#standardConcepts"><i class="fa fa-check"></i><b>5.2.6</b> 표준 개념</a></li>
<li class="chapter" data-level="5.2.7" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>5.2.7</b> 비 표준 개념</a></li>
<li class="chapter" data-level="5.2.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#--classification-concepts"><i class="fa fa-check"></i><b>5.2.8</b> 분류된 개념들 (Classification Concepts)</a></li>
<li class="chapter" data-level="5.2.9" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#--concept-codes"><i class="fa fa-check"></i><b>5.2.9</b> 개념 코드 (Concept Codes)</a></li>
<li class="chapter" data-level="5.2.10" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptLifeCycle"><i class="fa fa-check"></i><b>5.2.10</b> 수명 주기</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#section-5.3"><i class="fa fa-check"></i><b>5.3</b> 관계</a><ul>
<li class="chapter" data-level="5.3.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptMapping"><i class="fa fa-check"></i><b>5.3.1</b> 매핑 관계</a></li>
<li class="chapter" data-level="5.3.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>5.3.2</b> 계층적 관계</a></li>
<li class="chapter" data-level="5.3.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>5.3.3</b> 다른 용어의 개념들 간 관계</a></li>
<li class="chapter" data-level="5.3.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>5.3.4</b> 동일 용어의 개념들 간 관계</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptAncestor"><i class="fa fa-check"></i><b>5.4</b> 계층</a></li>
<li class="chapter" data-level="5.5" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>5.5</b> 내부 참조 테이블</a></li>
<li class="chapter" data-level="5.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#specialSituations"><i class="fa fa-check"></i><b>5.6</b> 특수 상황</a><ul>
<li class="chapter" data-level="5.6.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#section-5.6.1"><i class="fa fa-check"></i><b>5.6.1</b> 성별</a></li>
<li class="chapter" data-level="5.6.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>5.6.2</b> 인종과 민족</a></li>
<li class="chapter" data-level="5.6.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----omop-conditions"><i class="fa fa-check"></i><b>5.6.3</b> 진단 코딩 체계 및 OMOP Conditions</a></li>
<li class="chapter" data-level="5.6.4" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>5.6.4</b> 처치 코드 시스템</a></li>
<li class="chapter" data-level="5.6.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#section-5.6.5"><i class="fa fa-check"></i><b>5.6.5</b> 기기</a></li>
<li class="chapter" data-level="5.6.6" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>5.6.6</b> 방문 서비스</a></li>
<li class="chapter" data-level="5.6.7" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>5.6.7</b> 제공자 및 전문의</a></li>
<li class="chapter" data-level="5.6.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>5.6.8</b> 특별한 요구사항이 있는 치료 영역</a></li>
<li class="chapter" data-level="5.6.9" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#rxNormExtension"><i class="fa fa-check"></i><b>5.6.9</b> 약물 도메인 내의 표준 개념</a></li>
<li class="chapter" data-level="5.6.10" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#null--"><i class="fa fa-check"></i><b>5.6.10</b> NULL 의 특색</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#-3"><i class="fa fa-check"></i><b>5.7</b> 요약</a></li>
<li class="chapter" data-level="5.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#section-5.8"><i class="fa fa-check"></i><b>5.8</b> 연습</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html"><i class="fa fa-check"></i><b>6</b> 추출 변환 적재</a><ul>
<li class="chapter" data-level="6.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#section-6.1"><i class="fa fa-check"></i><b>6.1</b> 서론</a></li>
<li class="chapter" data-level="6.2" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#-etl-"><i class="fa fa-check"></i><b>6.2</b> 1단계 : ETL 설계</a><ul>
<li class="chapter" data-level="6.2.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#--white-rabbit"><i class="fa fa-check"></i><b>6.2.1</b> 흰 토끼 (White Rabbit)</a></li>
<li class="chapter" data-level="6.2.2" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#---rabbit-in-a-hat"><i class="fa fa-check"></i><b>6.2.2</b> 모자 속 토끼 (Rabbit-In-a-Hat)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>6.3</b> 2 단계: 코드 매핑 생성</a><ul>
<li class="chapter" data-level="6.3.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#usagi"><i class="fa fa-check"></i><b>6.3.1</b> 우사기(Usagi)</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#-etl-"><i class="fa fa-check"></i><b>6.4</b> 3 단계: ETL 수행</a></li>
<li class="chapter" data-level="6.5" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>6.5</b> 4 단계: 질 관리</a></li>
<li class="chapter" data-level="6.6" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#etl--themis"><i class="fa fa-check"></i><b>6.6</b> ETL 협약과 THEMIS</a></li>
<li class="chapter" data-level="6.7" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#CDMandETLMaintenance"><i class="fa fa-check"></i><b>6.7</b> CDM과 ETL의 유지</a></li>
<li class="chapter" data-level="6.8" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#etl---"><i class="fa fa-check"></i><b>6.8</b> ETL에 대한 마지막 생각</a></li>
<li class="chapter" data-level="6.9" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#-4"><i class="fa fa-check"></i><b>6.9</b> 요약</a></li>
<li class="chapter" data-level="6.10" data-path="WhereToBegin.html"><a href="WhereToBegin.html#-1"><i class="fa fa-check"></i><b>6.10</b> 예제</a></li>
</ul></li>
<li class="part"><span><b>III Data Analytics</b></span></li>
<li class="chapter" data-level="7" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html"><i class="fa fa-check"></i><b>7</b> 데이터 분석 이용 사례</a><ul>
<li class="chapter" data-level="7.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>7.1</b> 특성 분석</a></li>
<li class="chapter" data-level="7.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>7.2</b> 인구 수준 추정</a></li>
<li class="chapter" data-level="7.3" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>7.3</b> 환자 수준 예측</a></li>
<li class="chapter" data-level="7.4" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>7.4</b> 고혈압 이용 사례 예</a><ul>
<li class="chapter" data-level="7.4.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>7.4.1</b> 특성 분석 질문</a></li>
<li class="chapter" data-level="7.4.2" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>7.4.2</b> 인구 수준 추정 질문</a></li>
<li class="chapter" data-level="7.4.3" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>7.4.3</b> 환자 수준 예측 질문</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>7.5</b> 관찰 연구의 한계</a><ul>
<li class="chapter" data-level="7.5.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>7.5.1</b> 잘못된 데이터</a></li>
<li class="chapter" data-level="7.5.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>7.5.2</b> 결측 데이터</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#-5"><i class="fa fa-check"></i><b>7.6</b> 요약</a></li>
<li class="chapter" data-level="7.7" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#section-7.7"><i class="fa fa-check"></i><b>7.7</b> 연습문제</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html"><i class="fa fa-check"></i><b>8</b> OHDSI Analytics Tools</a><ul>
<li class="chapter" data-level="8.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#analysisImplementation"><i class="fa fa-check"></i><b>8.1</b> Analysis Implementation</a></li>
<li class="chapter" data-level="8.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#analysis-strategies"><i class="fa fa-check"></i><b>8.2</b> Analysis Strategies</a></li>
<li class="chapter" data-level="8.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#atlas"><i class="fa fa-check"></i><b>8.3</b> ATLAS</a><ul>
<li class="chapter" data-level="8.3.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#security"><i class="fa fa-check"></i><b>8.3.1</b> Security</a></li>
<li class="chapter" data-level="8.3.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#documentation"><i class="fa fa-check"></i><b>8.3.2</b> Documentation</a></li>
<li class="chapter" data-level="8.3.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#how-to-install"><i class="fa fa-check"></i><b>8.3.3</b> How to Install</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#methods-library"><i class="fa fa-check"></i><b>8.4</b> Methods Library</a><ul>
<li class="chapter" data-level="8.4.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#support-for-large-scale-analytics"><i class="fa fa-check"></i><b>8.4.1</b> Support for Large-Scale Analytics</a></li>
<li class="chapter" data-level="8.4.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#BigDataSupport"><i class="fa fa-check"></i><b>8.4.2</b> Support for Big Data</a></li>
<li class="chapter" data-level="8.4.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#documentation-1"><i class="fa fa-check"></i><b>8.4.3</b> Documentation</a></li>
<li class="chapter" data-level="8.4.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#system-requirements"><i class="fa fa-check"></i><b>8.4.4</b> System Requirements</a></li>
<li class="chapter" data-level="8.4.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#installR"><i class="fa fa-check"></i><b>8.4.5</b> How to Install</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#deployment-strategies"><i class="fa fa-check"></i><b>8.5</b> Deployment Strategies</a><ul>
<li class="chapter" data-level="8.5.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#broadsea"><i class="fa fa-check"></i><b>8.5.1</b> Broadsea</a></li>
<li class="chapter" data-level="8.5.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#amazon-aws"><i class="fa fa-check"></i><b>8.5.2</b> Amazon AWS</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#-6"><i class="fa fa-check"></i><b>8.6</b> 요약</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="SqlAndR.html"><a href="SqlAndR.html"><i class="fa fa-check"></i><b>9</b> SQL and R</a><ul>
<li class="chapter" data-level="9.1" data-path="SqlAndR.html"><a href="SqlAndR.html#SqlRender"><i class="fa fa-check"></i><b>9.1</b> SqlRender</a><ul>
<li class="chapter" data-level="9.1.1" data-path="SqlAndR.html"><a href="SqlAndR.html#sql-parameterization"><i class="fa fa-check"></i><b>9.1.1</b> SQL Parameterization</a></li>
<li class="chapter" data-level="9.1.2" data-path="SqlAndR.html"><a href="SqlAndR.html#translation-to-other-sql-dialects"><i class="fa fa-check"></i><b>9.1.2</b> Translation to Other SQL Dialects</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="SqlAndR.html"><a href="SqlAndR.html#DatabaseConnector"><i class="fa fa-check"></i><b>9.2</b> DatabaseConnector</a><ul>
<li class="chapter" data-level="9.2.1" data-path="SqlAndR.html"><a href="SqlAndR.html#creating-a-connection"><i class="fa fa-check"></i><b>9.2.1</b> Creating a Connection</a></li>
<li class="chapter" data-level="9.2.2" data-path="SqlAndR.html"><a href="SqlAndR.html#querying"><i class="fa fa-check"></i><b>9.2.2</b> Querying</a></li>
<li class="chapter" data-level="9.2.3" data-path="SqlAndR.html"><a href="SqlAndR.html#querying-using-ffdf-objects"><i class="fa fa-check"></i><b>9.2.3</b> Querying Using Ffdf Objects</a></li>
<li class="chapter" data-level="9.2.4" data-path="SqlAndR.html"><a href="SqlAndR.html#querying-different-platforms-using-the-same-sql"><i class="fa fa-check"></i><b>9.2.4</b> Querying Different Platforms Using the Same SQL</a></li>
<li class="chapter" data-level="9.2.5" data-path="SqlAndR.html"><a href="SqlAndR.html#inserting-tables"><i class="fa fa-check"></i><b>9.2.5</b> Inserting Tables</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="SqlAndR.html"><a href="SqlAndR.html#QueryTheCdm"><i class="fa fa-check"></i><b>9.3</b> Querying the CDM</a></li>
<li class="chapter" data-level="9.4" data-path="SqlAndR.html"><a href="SqlAndR.html#using-the-vocabulary-when-querying"><i class="fa fa-check"></i><b>9.4</b> Using the Vocabulary When Querying</a></li>
<li class="chapter" data-level="9.5" data-path="SqlAndR.html"><a href="SqlAndR.html#querylibrary"><i class="fa fa-check"></i><b>9.5</b> QueryLibrary</a></li>
<li class="chapter" data-level="9.6" data-path="SqlAndR.html"><a href="SqlAndR.html#designing-a-simple-study"><i class="fa fa-check"></i><b>9.6</b> Designing a Simple Study</a><ul>
<li class="chapter" data-level="9.6.1" data-path="SqlAndR.html"><a href="SqlAndR.html#problem-definition"><i class="fa fa-check"></i><b>9.6.1</b> Problem Definition</a></li>
<li class="chapter" data-level="9.6.2" data-path="SqlAndR.html"><a href="SqlAndR.html#exposure"><i class="fa fa-check"></i><b>9.6.2</b> Exposure</a></li>
<li class="chapter" data-level="9.6.3" data-path="SqlAndR.html"><a href="SqlAndR.html#outcome"><i class="fa fa-check"></i><b>9.6.3</b> Outcome</a></li>
<li class="chapter" data-level="9.6.4" data-path="SqlAndR.html"><a href="SqlAndR.html#time-at-risk"><i class="fa fa-check"></i><b>9.6.4</b> Time-At-Risk</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="SqlAndR.html"><a href="SqlAndR.html#implementing-the-study-using-sql-and-r"><i class="fa fa-check"></i><b>9.7</b> Implementing the Study Using SQL and R</a><ul>
<li class="chapter" data-level="9.7.1" data-path="SqlAndR.html"><a href="SqlAndR.html#exposure-cohort"><i class="fa fa-check"></i><b>9.7.1</b> Exposure Cohort</a></li>
<li class="chapter" data-level="9.7.2" data-path="SqlAndR.html"><a href="SqlAndR.html#outcome-cohort"><i class="fa fa-check"></i><b>9.7.2</b> Outcome Cohort</a></li>
<li class="chapter" data-level="9.7.3" data-path="SqlAndR.html"><a href="SqlAndR.html#incidence-rate-calculation"><i class="fa fa-check"></i><b>9.7.3</b> Incidence Rate Calculation</a></li>
<li class="chapter" data-level="9.7.4" data-path="SqlAndR.html"><a href="SqlAndR.html#clean-up"><i class="fa fa-check"></i><b>9.7.4</b> Clean Up</a></li>
<li class="chapter" data-level="9.7.5" data-path="SqlAndR.html"><a href="SqlAndR.html#compatibility"><i class="fa fa-check"></i><b>9.7.5</b> Compatibility</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="SqlAndR.html"><a href="SqlAndR.html#-7"><i class="fa fa-check"></i><b>9.8</b> 요약</a></li>
<li class="chapter" data-level="9.9" data-path="SqlAndR.html"><a href="SqlAndR.html#exercises"><i class="fa fa-check"></i><b>9.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="Cohorts.html"><a href="Cohorts.html"><i class="fa fa-check"></i><b>10</b> 코호트 만들기</a><ul>
<li class="chapter" data-level="10.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>10.1</b> 코호트란 무엇인가?</a></li>
<li class="chapter" data-level="10.2" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>10.2</b> 규칙 기반 코호트 정의</a></li>
<li class="chapter" data-level="10.3" data-path="Cohorts.html"><a href="Cohorts.html#conceptSets"><i class="fa fa-check"></i><b>10.3</b> 컨셉 모음</a></li>
<li class="chapter" data-level="10.4" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>10.4</b> 확률적 코호트 정의</a></li>
<li class="chapter" data-level="10.5" data-path="Cohorts.html"><a href="Cohorts.html#cohort-definition-validity"><i class="fa fa-check"></i><b>10.5</b> Cohort Definition Validity</a><ul>
<li class="chapter" data-level="10.5.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>10.5.1</b> 오디시의 골드 스탠다드 코호트 라이브러리</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>10.6</b> 고혈압 환자 코호트 작성하기</a></li>
<li class="chapter" data-level="10.7" data-path="Cohorts.html"><a href="Cohorts.html#atlas---"><i class="fa fa-check"></i><b>10.7</b> ATLAS를 이용해 코호트 작성하기</a><ul>
<li class="chapter" data-level="10.7.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>10.7.1</b> 초기 이벤트 기준</a></li>
<li class="chapter" data-level="10.7.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>10.7.2</b> 컨셉 모음 정의하기</a></li>
<li class="chapter" data-level="10.7.3" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>10.7.3</b> 추가적 초기 이벤트 기준</a></li>
<li class="chapter" data-level="10.7.4" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>10.7.4</b> 포함 기준</a></li>
<li class="chapter" data-level="10.7.5" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>10.7.5</b> 코호트 종료 기준</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="Cohorts.html"><a href="Cohorts.html#sql---"><i class="fa fa-check"></i><b>10.8</b> SQL을 사용하여 코호트 구현하기</a><ul>
<li class="chapter" data-level="10.8.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>10.8.1</b> 데이터베이스에 연결하기</a></li>
<li class="chapter" data-level="10.8.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>10.8.2</b> 컨셉 결정하기</a></li>
<li class="chapter" data-level="10.8.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>10.8.3</b> 약물을 처음 복용한 환자 찾기</a></li>
<li class="chapter" data-level="10.8.4" data-path="Cohorts.html"><a href="Cohorts.html#----365----"><i class="fa fa-check"></i><b>10.8.4</b> 약물 복용 이전 최소 365일동안 관찰될 수 있었던 환자</a></li>
<li class="chapter" data-level="10.8.5" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>10.8.5</b> 이전에 고혈압을 진단받은 환자</a></li>
<li class="chapter" data-level="10.8.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>10.8.6</b> 사전에 받은 치료가 없어야 함</a></li>
<li class="chapter" data-level="10.8.7" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>10.8.7</b> 단독 요법</a></li>
<li class="chapter" data-level="10.8.8" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>10.8.8</b> 코호트 종료</a></li>
<li class="chapter" data-level="10.8.9" data-path="Cohorts.html"><a href="Cohorts.html#section-10.8.9"><i class="fa fa-check"></i><b>10.8.9</b> 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="Cohorts.html"><a href="Cohorts.html#-8"><i class="fa fa-check"></i><b>10.9</b> 요약</a></li>
<li class="chapter" data-level="10.10" data-path="Cohorts.html"><a href="Cohorts.html#section-10.10"><i class="fa fa-check"></i><b>10.10</b> 실습</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Characterization.html"><a href="Characterization.html"><i class="fa fa-check"></i><b>11</b> 환자 특성 분석 Characterization</a><ul>
<li class="chapter" data-level="11.1" data-path="Characterization.html"><a href="Characterization.html#----database-level-characterization"><i class="fa fa-check"></i><b>11.1</b> 데이터베이스 수준의 특성 분석 (Database Level Characterization)</a></li>
<li class="chapter" data-level="11.2" data-path="Characterization.html"><a href="Characterization.html#---cohort-characterization"><i class="fa fa-check"></i><b>11.2</b> 코호트 특성 분석 (Cohort Characterization)</a></li>
<li class="chapter" data-level="11.3" data-path="Characterization.html"><a href="Characterization.html#--treatment-pathways"><i class="fa fa-check"></i><b>11.3</b> 치료 경로 (Treatment Pathways)</a></li>
<li class="chapter" data-level="11.4" data-path="Characterization.html"><a href="Characterization.html#-incidence"><i class="fa fa-check"></i><b>11.4</b> 발생 (Incidence)</a></li>
<li class="chapter" data-level="11.5" data-path="Characterization.html"><a href="Characterization.html#----characterizing-hypertensive-persons"><i class="fa fa-check"></i><b>11.5</b> 고혈압 환자의 특성 분석 (Characterizing Hypertensive Persons)</a></li>
<li class="chapter" data-level="11.6" data-path="Characterization.html"><a href="Characterization.html#atlas-----database-characterization-in-atlas"><i class="fa fa-check"></i><b>11.6</b> ATLAS를 활용한 데이터베이스의 특성 분석 (Database Characterization in ATLAS)</a></li>
<li class="chapter" data-level="11.7" data-path="Characterization.html"><a href="Characterization.html#atlas-----cohort-characterization-in-atlas"><i class="fa fa-check"></i><b>11.7</b> ATLAS를 이용한 코호트 특성 분석 (Cohort Characterization in ATLAS)</a><ul>
<li class="chapter" data-level="11.7.1" data-path="Characterization.html"><a href="Characterization.html#-design"><i class="fa fa-check"></i><b>11.7.1</b> 디자인 (Design)</a></li>
<li class="chapter" data-level="11.7.2" data-path="Characterization.html"><a href="Characterization.html#-executions"><i class="fa fa-check"></i><b>11.7.2</b> 실행 (Executions)</a></li>
<li class="chapter" data-level="11.7.3" data-path="Characterization.html"><a href="Characterization.html#-results"><i class="fa fa-check"></i><b>11.7.3</b> 결과 (Results)</a></li>
<li class="chapter" data-level="11.7.4" data-path="Characterization.html"><a href="Characterization.html#---defining-custom-features"><i class="fa fa-check"></i><b>11.7.4</b> 사용자 정의 속성 (Defining Custom Features)</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="Characterization.html"><a href="Characterization.html#r-----cohort-characterization-in-r"><i class="fa fa-check"></i><b>11.8</b> R을 이용한 코호트 특성 분석 (Cohort Characterization in R)</a><ul>
<li class="chapter" data-level="11.8.1" data-path="Characterization.html"><a href="Characterization.html#cohort-instantiation"><i class="fa fa-check"></i><b>11.8.1</b> Cohort Instantiation</a></li>
<li class="chapter" data-level="11.8.2" data-path="Characterization.html"><a href="Characterization.html#--data-extraction"><i class="fa fa-check"></i><b>11.8.2</b> 데이터 추출 (Data Extraction)</a></li>
<li class="chapter" data-level="11.8.3" data-path="Characterization.html"><a href="Characterization.html#----using-prespecified-analyses"><i class="fa fa-check"></i><b>11.8.3</b> 사전 지정 분석의 사용 (Using Prespecified Analyses)</a></li>
<li class="chapter" data-level="11.8.4" data-path="Characterization.html"><a href="Characterization.html#---creating-aggregated-covariates"><i class="fa fa-check"></i><b>11.8.4</b> 통합된 변수의 생성 (Creating Aggregated Covariates)</a></li>
<li class="chapter" data-level="11.8.5" data-path="Characterization.html"><a href="Characterization.html#--output-format"><i class="fa fa-check"></i><b>11.8.5</b> 결과 형식 (Output Format)</a></li>
<li class="chapter" data-level="11.8.6" data-path="Characterization.html"><a href="Characterization.html#---custom-covariates"><i class="fa fa-check"></i><b>11.8.6</b> 사용자 정의 변수 (Custom Covariates)</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="Characterization.html"><a href="Characterization.html#atlas---cohort-pathways-in-atlas"><i class="fa fa-check"></i><b>11.9</b> ATLAS에서 코호트 경로 (Cohort Pathways in ATLAS)</a><ul>
<li class="chapter" data-level="11.9.1" data-path="Characterization.html"><a href="Characterization.html#-design-1"><i class="fa fa-check"></i><b>11.9.1</b> 디자인 (Design)</a></li>
<li class="chapter" data-level="11.9.2" data-path="Characterization.html"><a href="Characterization.html#-executions-1"><i class="fa fa-check"></i><b>11.9.2</b> 실행 (Executions)</a></li>
<li class="chapter" data-level="11.9.3" data-path="Characterization.html"><a href="Characterization.html#--viewing-results"><i class="fa fa-check"></i><b>11.9.3</b> 결과 확인 (Viewing Results)</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="Characterization.html"><a href="Characterization.html#atlas----incidence-analysis-in-atlas"><i class="fa fa-check"></i><b>11.10</b> ATLAS를 이용한 발생 분석 (Incidence Analysis in ATLAS)</a><ul>
<li class="chapter" data-level="11.10.1" data-path="Characterization.html"><a href="Characterization.html#-design-2"><i class="fa fa-check"></i><b>11.10.1</b> 디자인 (Design)</a></li>
<li class="chapter" data-level="11.10.2" data-path="Characterization.html"><a href="Characterization.html#-executions-2"><i class="fa fa-check"></i><b>11.10.2</b> 실행 (Executions)</a></li>
<li class="chapter" data-level="11.10.3" data-path="Characterization.html"><a href="Characterization.html#--viewing-results-1"><i class="fa fa-check"></i><b>11.10.3</b> 결과 확인 (Viewing Results)</a></li>
</ul></li>
<li class="chapter" data-level="11.11" data-path="Characterization.html"><a href="Characterization.html#-9"><i class="fa fa-check"></i><b>11.11</b> 요약</a></li>
<li class="chapter" data-level="11.12" data-path="Characterization.html"><a href="Characterization.html#-exercises"><i class="fa fa-check"></i><b>11.12</b> 실습 (Exercises)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html"><i class="fa fa-check"></i><b>12</b> Population-Level Estimation</a><ul>
<li class="chapter" data-level="12.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#CohortMethod"><i class="fa fa-check"></i><b>12.1</b> The Cohort Method Design</a><ul>
<li class="chapter" data-level="12.1.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#propensity-scores"><i class="fa fa-check"></i><b>12.1.1</b> Propensity Scores</a></li>
<li class="chapter" data-level="12.1.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#VariableSelection"><i class="fa fa-check"></i><b>12.1.2</b> Variable Selection</a></li>
<li class="chapter" data-level="12.1.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#caliper"><i class="fa fa-check"></i><b>12.1.3</b> Caliper</a></li>
<li class="chapter" data-level="12.1.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#overlap-preference-scores"><i class="fa fa-check"></i><b>12.1.4</b> Overlap: Preference Scores</a></li>
<li class="chapter" data-level="12.1.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#balance"><i class="fa fa-check"></i><b>12.1.5</b> Balance</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#-----the-self-controlled-cohort-design"><i class="fa fa-check"></i><b>12.2</b> 자가 통제 코호트 연구 설계 (The Self-Controlled Cohort Design)</a></li>
<li class="chapter" data-level="12.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#----the-case-control-design"><i class="fa fa-check"></i><b>12.3</b> 환자-대조군 연구 설계 (The Case-Control Design)</a></li>
<li class="chapter" data-level="12.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#----the-case-crossover-design"><i class="fa fa-check"></i><b>12.4</b> 환자-교차 연구 설계 (The Case-Crossover Design)</a></li>
<li class="chapter" data-level="12.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#-----the-self-controlled-case-series-design"><i class="fa fa-check"></i><b>12.5</b> 자기 대조군 환자군 연구 설계 (The Self-Controlled Case Series Design)</a></li>
<li class="chapter" data-level="12.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#designing-a-hypertension-study"><i class="fa fa-check"></i><b>12.6</b> Designing a Hypertension Study</a><ul>
<li class="chapter" data-level="12.6.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#problem-definition-1"><i class="fa fa-check"></i><b>12.6.1</b> Problem Definition</a></li>
<li class="chapter" data-level="12.6.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#target-and-comparator"><i class="fa fa-check"></i><b>12.6.2</b> Target and Comparator</a></li>
<li class="chapter" data-level="12.6.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#outcome-1"><i class="fa fa-check"></i><b>12.6.3</b> Outcome</a></li>
<li class="chapter" data-level="12.6.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#time-at-risk-1"><i class="fa fa-check"></i><b>12.6.4</b> Time-At-Risk</a></li>
<li class="chapter" data-level="12.6.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#model"><i class="fa fa-check"></i><b>12.6.5</b> Model</a></li>
<li class="chapter" data-level="12.6.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#study-summary"><i class="fa fa-check"></i><b>12.6.6</b> Study Summary</a></li>
<li class="chapter" data-level="12.6.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#control-questions"><i class="fa fa-check"></i><b>12.6.7</b> Control Questions</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#PleAtlas"><i class="fa fa-check"></i><b>12.7</b> Implementing the Study Using ATLAS</a><ul>
<li class="chapter" data-level="12.7.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#ComparisonSettings"><i class="fa fa-check"></i><b>12.7.1</b> Comparative Cohort Settings</a></li>
<li class="chapter" data-level="12.7.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#effect-estimation-analysis-settings"><i class="fa fa-check"></i><b>12.7.2</b> Effect Estimation Analysis Settings</a></li>
<li class="chapter" data-level="12.7.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#evaluationSettings"><i class="fa fa-check"></i><b>12.7.3</b> Evaluation Settings</a></li>
<li class="chapter" data-level="12.7.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#--running-the-study-package"><i class="fa fa-check"></i><b>12.7.4</b> 연구 패키지 실행(Running the study package)</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#pleR"><i class="fa fa-check"></i><b>12.8</b> Implementing the Study Using R</a><ul>
<li class="chapter" data-level="12.8.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#--cohort-instantiation"><i class="fa fa-check"></i><b>12.8.1</b> 코호트 실체화 (Cohort Instantiation)</a></li>
<li class="chapter" data-level="12.8.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#--data-extraction-1"><i class="fa fa-check"></i><b>12.8.2</b> 데이터 추출 (Data Extraction)</a></li>
<li class="chapter" data-level="12.8.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#----defining-the-study-population"><i class="fa fa-check"></i><b>12.8.3</b> 연구 대상 집단 정의 (Defining the Study Population)</a></li>
<li class="chapter" data-level="12.8.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#--propensity-scores"><i class="fa fa-check"></i><b>12.8.4</b> 성향 점수 (Propensity Scores)</a></li>
<li class="chapter" data-level="12.8.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#outcome-models"><i class="fa fa-check"></i><b>12.8.5</b> Outcome Models</a></li>
<li class="chapter" data-level="12.8.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#MultipleAnalyses"><i class="fa fa-check"></i><b>12.8.6</b> Running Multiple Analyses</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#studyOutputs"><i class="fa fa-check"></i><b>12.9</b> 연구 결과 (Study Outputs)</a><ul>
<li class="chapter" data-level="12.9.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#----propensity-scores-and-model"><i class="fa fa-check"></i><b>12.9.1</b> 성향 점수 및 모델 (Propensity Scores and Model)</a></li>
<li class="chapter" data-level="12.9.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#covariate-balance"><i class="fa fa-check"></i><b>12.9.2</b> Covariate Balance</a></li>
<li class="chapter" data-level="12.9.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#follow-up-and-power"><i class="fa fa-check"></i><b>12.9.3</b> Follow Up and Power</a></li>
<li class="chapter" data-level="12.9.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#kaplan-meier"><i class="fa fa-check"></i><b>12.9.4</b> Kaplan-Meier</a></li>
<li class="chapter" data-level="12.9.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#effect-size-estimate"><i class="fa fa-check"></i><b>12.9.5</b> Effect Size Estimate</a></li>
</ul></li>
<li class="chapter" data-level="12.10" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#-10"><i class="fa fa-check"></i><b>12.10</b> 요약</a></li>
<li class="chapter" data-level="12.11" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#exercises-1"><i class="fa fa-check"></i><b>12.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html"><i class="fa fa-check"></i><b>13</b> 환자-수준 예측</a><ul>
<li class="chapter" data-level="13.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.1</b> 예측 문제</a></li>
<li class="chapter" data-level="13.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.2</b> 데이터 추출</a><ul>
<li class="chapter" data-level="13.2.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.2.1</b> 데이터 추출 예제</a></li>
<li class="chapter" data-level="13.2.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#section-13.2.2"><i class="fa fa-check"></i><b>13.2.2</b> 결측</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#modelFitting"><i class="fa fa-check"></i><b>13.3</b> 모형 적합</a><ul>
<li class="chapter" data-level="13.3.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.3.1</b> 정규화된 로지스틱 회귀</a></li>
<li class="chapter" data-level="13.3.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#gradient-boosting-machines"><i class="fa fa-check"></i><b>13.3.2</b> Gradient Boosting Machines</a></li>
<li class="chapter" data-level="13.3.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#random-forest"><i class="fa fa-check"></i><b>13.3.3</b> Random Forest</a></li>
<li class="chapter" data-level="13.3.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#k---k-nearest-neighbor"><i class="fa fa-check"></i><b>13.3.4</b> K-최근접 이웃 (K-Nearest neighbor)</a></li>
<li class="chapter" data-level="13.3.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#--naive-bayes"><i class="fa fa-check"></i><b>13.3.5</b> 나이브 베이즈 (Naive Bayes)</a></li>
<li class="chapter" data-level="13.3.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#adaboost"><i class="fa fa-check"></i><b>13.3.6</b> AdaBoost</a></li>
<li class="chapter" data-level="13.3.7" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.3.7</b> 의사 결정 트리</a></li>
<li class="chapter" data-level="13.3.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#multilayer-perceptron"><i class="fa fa-check"></i><b>13.3.8</b> Multilayer Perceptron</a></li>
<li class="chapter" data-level="13.3.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#--deep-learning"><i class="fa fa-check"></i><b>13.3.9</b> 딥 러닝 (Deep Learning)</a></li>
<li class="chapter" data-level="13.3.10" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.3.10</b> 다른 알고리즘</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.4</b> 예측 모형 평가</a><ul>
<li class="chapter" data-level="13.4.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.4.1</b> 평가 유형</a></li>
<li class="chapter" data-level="13.4.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#performance"><i class="fa fa-check"></i><b>13.4.2</b> 성능 지표</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>13.5</b> 환자-수준 예측 연구 설계</a><ul>
<li class="chapter" data-level="13.5.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.5.1</b> 문제 정의</a></li>
<li class="chapter" data-level="13.5.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.5.2</b> 연구 모집단 정의</a></li>
<li class="chapter" data-level="13.5.3" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.5.3</b> 모형 개발 설정</a></li>
<li class="chapter" data-level="13.5.4" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.5.4</b> 모형 평가</a></li>
<li class="chapter" data-level="13.5.5" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.5.5</b> 연구 요약</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#implementing-the-study-in-atlas"><i class="fa fa-check"></i><b>13.6</b> Implementing the Study in ATLAS</a><ul>
<li class="chapter" data-level="13.6.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.6.1</b> 예측 문제 설정</a></li>
<li class="chapter" data-level="13.6.2" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.6.2</b> 분석 설정</a></li>
<li class="chapter" data-level="13.6.3" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.6.3</b> 실행 설정</a></li>
<li class="chapter" data-level="13.6.4" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.6.4</b> 학습 설정</a></li>
<li class="chapter" data-level="13.6.5" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>13.6.5</b> 연구 가져오기 및 내보내기</a></li>
<li class="chapter" data-level="13.6.6" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.6.6</b> 연구 패키지 다운로드</a></li>
<li class="chapter" data-level="13.6.7" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.6.7</b> 연구 실행</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#r--"><i class="fa fa-check"></i><b>13.7</b> R에서의 연구 실행</a><ul>
<li class="chapter" data-level="13.7.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.7.1</b> 코호트 예시화</a></li>
<li class="chapter" data-level="13.7.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#--1"><i class="fa fa-check"></i><b>13.7.2</b> 데이터 추출</a></li>
<li class="chapter" data-level="13.7.3" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>13.7.3</b> 추가 포함 기준</a></li>
<li class="chapter" data-level="13.7.4" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.7.4</b> 모형 개발</a></li>
<li class="chapter" data-level="13.7.5" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.7.5</b> 내부 검증</a></li>
<li class="chapter" data-level="13.7.6" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>13.7.6</b> 외부 검증</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#results-dissemination"><i class="fa fa-check"></i><b>13.8</b> Results Dissemination</a><ul>
<li class="chapter" data-level="13.8.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#model-performance"><i class="fa fa-check"></i><b>13.8.1</b> Model Performance</a></li>
<li class="chapter" data-level="13.8.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#comparing-models"><i class="fa fa-check"></i><b>13.8.2</b> Comparing Models</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#additional-patient-level-prediction-features"><i class="fa fa-check"></i><b>13.9</b> Additional Patient-Level Prediction Features</a><ul>
<li class="chapter" data-level="13.9.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#journal-paper-generation"><i class="fa fa-check"></i><b>13.9.1</b> Journal Paper Generation</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#-11"><i class="fa fa-check"></i><b>13.10</b> 요약</a></li>
<li class="chapter" data-level="13.11" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#exercises-2"><i class="fa fa-check"></i><b>13.11</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>IV Evidence Quality</b></span></li>
<li class="chapter" data-level="14" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html"><i class="fa fa-check"></i><b>14</b> Evidence Quality</a><ul>
<li class="chapter" data-level="14.1" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#attributes-of-reliable-evidence----"><i class="fa fa-check"></i><b>14.1</b> Attributes of Reliable Evidence (신뢰성을 위한 근거의 속성)</a></li>
<li class="chapter" data-level="14.2" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>14.2</b> 근거의 질에 대한 이해</a></li>
<li class="chapter" data-level="14.3" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>14.3</b> 근거 품질의 전달</a></li>
<li class="chapter" data-level="14.4" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#-12"><i class="fa fa-check"></i><b>14.4</b> 요약</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="DataQuality.html"><a href="DataQuality.html"><i class="fa fa-check"></i><b>15</b> Data Quality</a><ul>
<li class="chapter" data-level="15.1" data-path="DataQuality.html"><a href="DataQuality.html#-----sources-of-data-quality-problems"><i class="fa fa-check"></i><b>15.1</b> 데이터 품질 문제에 대한 원인 (Sources of Data Quality Problems)</a></li>
<li class="chapter" data-level="15.2" data-path="DataQuality.html"><a href="DataQuality.html#---data-quality-in-general"><i class="fa fa-check"></i><b>15.2</b> 보편적인 데이터 품질 (Data Quality in General)</a><ul>
<li class="chapter" data-level="15.2.1" data-path="DataQuality.html"><a href="DataQuality.html#--checks-data-qualityintegrate-checks"><i class="fa fa-check"></i><b>15.2.1</b> 데이터 품질 checks (Data Qualityintegrate Checks)</a></li>
<li class="chapter" data-level="15.2.2" data-path="DataQuality.html"><a href="DataQuality.html#etlUnitTests"><i class="fa fa-check"></i><b>15.2.2</b> ETL Unit Tests</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="DataQuality.html"><a href="DataQuality.html#--checks-study-specific-checks"><i class="fa fa-check"></i><b>15.3</b> 연구 목적 checks (Study-Specific Checks)</a><ul>
<li class="chapter" data-level="15.3.1" data-path="DataQuality.html"><a href="DataQuality.html#checking-mappings"><i class="fa fa-check"></i><b>15.3.1</b> Checking Mappings</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="DataQuality.html"><a href="DataQuality.html#achillesInPractice"><i class="fa fa-check"></i><b>15.4</b> ACHILLES 실습 (ACHILLES in Practice)</a></li>
<li class="chapter" data-level="15.5" data-path="DataQuality.html"><a href="DataQuality.html#dqdInPractice"><i class="fa fa-check"></i><b>15.5</b> Data Quality Dashboard 실습 (Data Quality Dashboard in Practice)</a></li>
<li class="chapter" data-level="15.6" data-path="DataQuality.html"><a href="DataQuality.html#--checks--study-specific-checks-in-practice"><i class="fa fa-check"></i><b>15.6</b> 연구 목적 checks 실습 (Study-Specific Checks in Practice)</a></li>
<li class="chapter" data-level="15.7" data-path="DataQuality.html"><a href="DataQuality.html#-13"><i class="fa fa-check"></i><b>15.7</b> 요약</a></li>
<li class="chapter" data-level="15.8" data-path="DataQuality.html"><a href="DataQuality.html#exercises-3"><i class="fa fa-check"></i><b>15.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html"><i class="fa fa-check"></i><b>16</b> Clinical Validity</a><ul>
<li class="chapter" data-level="16.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#CharacteristicsOfDatabase"><i class="fa fa-check"></i><b>16.1</b> 보건의료 데이터의 특성 (Characteristics of Health Care Databases)</a></li>
<li class="chapter" data-level="16.2" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#CohortValidation"><i class="fa fa-check"></i><b>16.2</b> Cohort Validation</a><ul>
<li class="chapter" data-level="16.2.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>16.2.1</b> 코호트 판단 측정기준</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>16.3</b> 원천 기록 검증</a><ul>
<li class="chapter" data-level="16.3.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>16.3.1</b> 원천 기록 검증에 대한 예시</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#phevaluator"><i class="fa fa-check"></i><b>16.4</b> PheValuator</a><ul>
<li class="chapter" data-level="16.4.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#phevaluator---"><i class="fa fa-check"></i><b>16.4.1</b> PheValuator에 의한 검증 예시</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#GeneralizabilityOfEvidence"><i class="fa fa-check"></i><b>16.5</b> 근거의 일반화</a></li>
<li class="chapter" data-level="16.6" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#-14"><i class="fa fa-check"></i><b>16.6</b> 요약</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html"><i class="fa fa-check"></i><b>17</b> Software Validity</a><ul>
<li class="chapter" data-level="17.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>17.1</b> 분석 코드의 타당성</a><ul>
<li class="chapter" data-level="17.1.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#automation"><i class="fa fa-check"></i><b>17.1.1</b> 재현성 충족을 위한 자동화</a></li>
<li class="chapter" data-level="17.1.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>17.1.2</b> 프로그래밍 모범 사례</a></li>
<li class="chapter" data-level="17.1.3" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>17.1.3</b> 코드 검증</a></li>
<li class="chapter" data-level="17.1.4" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>17.1.4</b> 연구 방법론 라이브러리의 활용</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#-----"><i class="fa fa-check"></i><b>17.2</b> 연구 방법론 라이브러리 소프트웨어의 개발 과정</a><ul>
<li class="chapter" data-level="17.2.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>17.2.1</b> 소스 코드 관리</a></li>
<li class="chapter" data-level="17.2.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#section-17.2.2"><i class="fa fa-check"></i><b>17.2.2</b> 문서화</a></li>
<li class="chapter" data-level="17.2.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>17.2.3</b> 현재 및 과거 버전으로의 접근</a></li>
<li class="chapter" data-level="17.2.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>17.2.4</b> 유지 보수, 지원 및 중단</a></li>
<li class="chapter" data-level="17.2.5" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>17.2.5</b> 검증된 인력</a></li>
<li class="chapter" data-level="17.2.6" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>17.2.6</b> 물리적, 논리적 보안체계</a></li>
<li class="chapter" data-level="17.2.7" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>17.2.7</b> 복구 체계</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>17.3</b> 연구방법론 라이브러리 기능 검사</a><ul>
<li class="chapter" data-level="17.3.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>17.3.1</b> 단위 검사</a></li>
<li class="chapter" data-level="17.3.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#section-17.3.2"><i class="fa fa-check"></i><b>17.3.2</b> 모의시행</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#section-17.4"><i class="fa fa-check"></i><b>17.4</b> 정리</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="MethodValidity.html"><a href="MethodValidity.html"><i class="fa fa-check"></i><b>18</b> Method Validity</a><ul>
<li class="chapter" data-level="18.1" data-path="MethodValidity.html"><a href="MethodValidity.html#design-specific-diagnostics"><i class="fa fa-check"></i><b>18.1</b> Design-Specific Diagnostics</a></li>
<li class="chapter" data-level="18.2" data-path="MethodValidity.html"><a href="MethodValidity.html#diagnostics-for-all-estimation"><i class="fa fa-check"></i><b>18.2</b> Diagnostics for All Estimation</a><ul>
<li class="chapter" data-level="18.2.1" data-path="MethodValidity.html"><a href="MethodValidity.html#NegativeControls"><i class="fa fa-check"></i><b>18.2.1</b> Negative Controls</a></li>
<li class="chapter" data-level="18.2.2" data-path="MethodValidity.html"><a href="MethodValidity.html#PositiveControls"><i class="fa fa-check"></i><b>18.2.2</b> Positive Controls</a></li>
<li class="chapter" data-level="18.2.3" data-path="MethodValidity.html"><a href="MethodValidity.html#metrics"><i class="fa fa-check"></i><b>18.2.3</b> Empirical Evaluation</a></li>
<li class="chapter" data-level="18.2.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p-value-calibration"><i class="fa fa-check"></i><b>18.2.4</b> P-Value Calibration</a></li>
<li class="chapter" data-level="18.2.5" data-path="MethodValidity.html"><a href="MethodValidity.html#confidence-interval-calibration"><i class="fa fa-check"></i><b>18.2.5</b> Confidence Interval Calibration</a></li>
<li class="chapter" data-level="18.2.6" data-path="MethodValidity.html"><a href="MethodValidity.html#replication-across-sites"><i class="fa fa-check"></i><b>18.2.6</b> Replication Across Sites</a></li>
<li class="chapter" data-level="18.2.7" data-path="MethodValidity.html"><a href="MethodValidity.html#sensitivity-analyses"><i class="fa fa-check"></i><b>18.2.7</b> Sensitivity Analyses</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="MethodValidity.html"><a href="MethodValidity.html#method-validation-in-practice"><i class="fa fa-check"></i><b>18.3</b> Method Validation in Practice</a><ul>
<li class="chapter" data-level="18.3.1" data-path="MethodValidity.html"><a href="MethodValidity.html#selecting-negative-controls"><i class="fa fa-check"></i><b>18.3.1</b> Selecting Negative Controls</a></li>
<li class="chapter" data-level="18.3.2" data-path="MethodValidity.html"><a href="MethodValidity.html#including-controls"><i class="fa fa-check"></i><b>18.3.2</b> Including Controls</a></li>
<li class="chapter" data-level="18.3.3" data-path="MethodValidity.html"><a href="MethodValidity.html#empirical-performance"><i class="fa fa-check"></i><b>18.3.3</b> Empirical Performance</a></li>
<li class="chapter" data-level="18.3.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p-value-calibration-1"><i class="fa fa-check"></i><b>18.3.4</b> P-Value Calibration</a></li>
<li class="chapter" data-level="18.3.5" data-path="MethodValidity.html"><a href="MethodValidity.html#confidence-interval-calibration-1"><i class="fa fa-check"></i><b>18.3.5</b> Confidence Interval Calibration</a></li>
<li class="chapter" data-level="18.3.6" data-path="MethodValidity.html"><a href="MethodValidity.html#between-database-heterogeneity"><i class="fa fa-check"></i><b>18.3.6</b> Between-Database Heterogeneity</a></li>
<li class="chapter" data-level="18.3.7" data-path="MethodValidity.html"><a href="MethodValidity.html#sensitivity-analyses-1"><i class="fa fa-check"></i><b>18.3.7</b> Sensitivity Analyses</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="MethodValidity.html"><a href="MethodValidity.html#ohdsi-methods-benchmark"><i class="fa fa-check"></i><b>18.4</b> OHDSI Methods Benchmark</a></li>
<li class="chapter" data-level="18.5" data-path="MethodValidity.html"><a href="MethodValidity.html#-15"><i class="fa fa-check"></i><b>18.5</b> 요약</a></li>
</ul></li>
<li class="part"><span><b>V OHDSI Studies</b></span></li>
<li class="chapter" data-level="19" data-path="StudySteps.html"><a href="StudySteps.html"><i class="fa fa-check"></i><b>19</b> 연구단계</a><ul>
<li class="chapter" data-level="19.1" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>19.1</b> 일반 모범 사례 지침</a><ul>
<li class="chapter" data-level="19.1.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>19.1.1</b> 관찰 연구 정의</a></li>
<li class="chapter" data-level="19.1.2" data-path="index.html"><a href="index.html#---"><i class="fa fa-check"></i><b>19.1.2</b> 연구 설계의 사전 지정</a></li>
<li class="chapter" data-level="19.1.3" data-path="StudySteps.html"><a href="StudySteps.html#section-19.1.3"><i class="fa fa-check"></i><b>19.1.3</b> 프로토콜</a></li>
<li class="chapter" data-level="19.1.4" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>19.1.4</b> 표준화된 분석</a></li>
<li class="chapter" data-level="19.1.5" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>19.1.5</b> 연구 패키지</a></li>
<li class="chapter" data-level="19.1.6" data-path="StudySteps.html"><a href="StudySteps.html#cdm---"><i class="fa fa-check"></i><b>19.1.6</b> CDM의 기초가 되는 데이터</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>19.2</b> 세부 연구 단계</a><ul>
<li class="chapter" data-level="19.2.1" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>19.2.1</b> 질문 정의</a></li>
<li class="chapter" data-level="19.2.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>19.2.2</b> 데이터 가용성 및 품질 검토</a></li>
<li class="chapter" data-level="19.2.3" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>19.2.3</b> 연구 집단</a></li>
<li class="chapter" data-level="19.2.4" data-path="StudySteps.html"><a href="StudySteps.html#Feasibility"><i class="fa fa-check"></i><b>19.2.4</b> 실행 가능성 및 진단</a></li>
<li class="chapter" data-level="19.2.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>19.2.5</b> 프로토콜 및 연구 패키지 마무리</a></li>
<li class="chapter" data-level="19.2.6" data-path="index.html"><a href="index.html#-"><i class="fa fa-check"></i><b>19.2.6</b> 연구 수행</a></li>
<li class="chapter" data-level="19.2.7" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>19.2.7</b> 해석 및 작성</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="StudySteps.html"><a href="StudySteps.html#-16"><i class="fa fa-check"></i><b>19.3</b> 요약</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="NetworkResearch.html"><a href="NetworkResearch.html"><i class="fa fa-check"></i><b>20</b> OHDSI Network Research</a><ul>
<li class="chapter" data-level="20.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#--ohdsi"><i class="fa fa-check"></i><b>20.1</b> 연구 네트워크로서의 OHDSI</a></li>
<li class="chapter" data-level="20.2" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi--"><i class="fa fa-check"></i><b>20.2</b> OHDSI 네트워크 연구</a><ul>
<li class="chapter" data-level="20.2.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi----"><i class="fa fa-check"></i><b>20.2.1</b> OHDSI 네트워크 연구가 필요한 이유</a></li>
<li class="chapter" data-level="20.2.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi---"><i class="fa fa-check"></i><b>20.2.2</b> OHDSI 네트워크 연구의 정의</a></li>
<li class="chapter" data-level="20.2.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi------"><i class="fa fa-check"></i><b>20.2.3</b> OHDSI 네트워크 연구 설계를 위한 고려 사항</a></li>
<li class="chapter" data-level="20.2.4" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi-----"><i class="fa fa-check"></i><b>20.2.4</b> OHDSI 네트워크 연구를 위한 논리적 관점</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi---"><i class="fa fa-check"></i><b>20.3</b> OHDSI 네트워크 연구 수행하기</a><ul>
<li class="chapter" data-level="20.3.1" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>20.3.1</b> 연구 설계와 타당성</a></li>
<li class="chapter" data-level="20.3.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#--1"><i class="fa fa-check"></i><b>20.3.2</b> 연구 실행</a></li>
<li class="chapter" data-level="20.3.3" data-path="index.html"><a href="index.html#--"><i class="fa fa-check"></i><b>20.3.3</b> 결과의 보급와 출판</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#----"><i class="fa fa-check"></i><b>20.4</b> 미래의 모습: 네트워크 연구의 자동화</a></li>
<li class="chapter" data-level="20.5" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi---"><i class="fa fa-check"></i><b>20.5</b> OHDSI 네트워크 연구의 정석</a></li>
<li class="chapter" data-level="20.6" data-path="NetworkResearch.html"><a href="NetworkResearch.html#-17"><i class="fa fa-check"></i><b>20.6</b> 요약</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="Glossary.html"><a href="Glossary.html"><i class="fa fa-check"></i><b>A</b> Glossary</a></li>
<li class="chapter" data-level="B" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html"><i class="fa fa-check"></i><b>B</b> Cohort definitions</a><ul>
<li class="chapter" data-level="B.1" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitors"><i class="fa fa-check"></i><b>B.1</b> ACE Inhibitors</a></li>
<li class="chapter" data-level="B.2" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitorsMono"><i class="fa fa-check"></i><b>B.2</b> New Users of ACE Inhibitors Monotherapy</a></li>
<li class="chapter" data-level="B.3" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Ami"><i class="fa fa-check"></i><b>B.3</b> Acute Myocardial Infarction (AMI)</a></li>
<li class="chapter" data-level="B.4" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Angioedema"><i class="fa fa-check"></i><b>B.4</b> Angioedema</a></li>
<li class="chapter" data-level="B.5" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ThiazidesMono"><i class="fa fa-check"></i><b>B.5</b> New Users of Thiazide-Like Diuretics Monotherapy</a></li>
<li class="chapter" data-level="B.6" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#HTN1yrFO"><i class="fa fa-check"></i><b>B.6</b> Patients Initiating First-Line Therapy for Hypertension</a></li>
<li class="chapter" data-level="B.7" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#HTN3yrFO"><i class="fa fa-check"></i><b>B.7</b> Patients Initiating First-Line Therapy for Hypertension With &gt;3 Yr Follow-Up</a></li>
<li class="chapter" data-level="B.8" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ACEiUse"><i class="fa fa-check"></i><b>B.8</b> ACE Inhibitor Use</a></li>
<li class="chapter" data-level="B.9" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ARBUse"><i class="fa fa-check"></i><b>B.9</b> Angiotensin Receptor Blocker (ARB) Use</a></li>
<li class="chapter" data-level="B.10" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#THZUse"><i class="fa fa-check"></i><b>B.10</b> Thiazide Or Thiazide-Like Diuretic Use</a></li>
<li class="chapter" data-level="B.11" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#dCCBUse"><i class="fa fa-check"></i><b>B.11</b> Dihydropyridine Calcium Channel Blocker (dCCB) Use</a></li>
<li class="chapter" data-level="B.12" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ndCCBUse"><i class="fa fa-check"></i><b>B.12</b> Non-Dihydropyridine Calcium Channel Blocker (ndCCB) Use</a></li>
<li class="chapter" data-level="B.13" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#BBUse"><i class="fa fa-check"></i><b>B.13</b> Beta-Blocker Use</a></li>
<li class="chapter" data-level="B.14" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#DLoopUse"><i class="fa fa-check"></i><b>B.14</b> Diuretic-Loop Use</a></li>
<li class="chapter" data-level="B.15" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#DPUse"><i class="fa fa-check"></i><b>B.15</b> Diuretic-Potassium Sparing Use</a></li>
<li class="chapter" data-level="B.16" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#A1BUse"><i class="fa fa-check"></i><b>B.16</b> Alpha-1 Blocker Use</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="NegativeControlsAppendix.html"><a href="NegativeControlsAppendix.html"><i class="fa fa-check"></i><b>C</b> Negative controls</a><ul>
<li class="chapter" data-level="C.1" data-path="NegativeControlsAppendix.html"><a href="NegativeControlsAppendix.html#AceiThzNsc"><i class="fa fa-check"></i><b>C.1</b> ACEi and THZ</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="ProtocolTemplate.html"><a href="ProtocolTemplate.html"><i class="fa fa-check"></i><b>D</b> Protocol template</a></li>
<li class="chapter" data-level="E" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html"><i class="fa fa-check"></i><b>E</b> Suggested Answers</a><ul>
<li class="chapter" data-level="E.1" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Cdmanswers"><i class="fa fa-check"></i><b>E.1</b> The Common Data Model</a></li>
<li class="chapter" data-level="E.2" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Vocabanswers"><i class="fa fa-check"></i><b>E.2</b> Standardized Vocabularies</a></li>
<li class="chapter" data-level="E.3" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Etlanswers"><i class="fa fa-check"></i><b>E.3</b> Extract Transform Load</a></li>
<li class="chapter" data-level="E.4" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#UseCasesanswers"><i class="fa fa-check"></i><b>E.4</b> Data Analytics Use Cases</a></li>
<li class="chapter" data-level="E.5" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#SqlAndRanswers"><i class="fa fa-check"></i><b>E.5</b> SQL and R</a></li>
<li class="chapter" data-level="E.6" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Cohortsanswers"><i class="fa fa-check"></i><b>E.6</b> Defining Cohorts</a></li>
<li class="chapter" data-level="E.7" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Characterizationanswers"><i class="fa fa-check"></i><b>E.7</b> Characterization</a></li>
<li class="chapter" data-level="E.8" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Pleanswers"><i class="fa fa-check"></i><b>E.8</b> Population-Level Estimation</a></li>
<li class="chapter" data-level="E.9" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Plpanswers"><i class="fa fa-check"></i><b>E.9</b> Patient-Level Prediction</a></li>
<li class="chapter" data-level="E.10" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#DataQualityanswers"><i class="fa fa-check"></i><b>E.10</b> Data Quality</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Book of OHDSI Korea</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="PatientLevelPrediction" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> 환자-수준 예측</h1>
<p><em>Chapter leads: Peter Rijnbeek &amp; Jenna Reps</em></p>

<p>임상의사결정(clinical decision making)이란 임상의사가 알 수 있는 환자의 병력에 대한 정보와 현재 임상지침에 따라 진단 또는 치료 경로를 추론해야하는 복잡한 일이다. 임상 예측 모형은 이러한 의사 결정 과정을 지원하기 위해 개발되었으며 광범위한 전문 분야에서 임상 실무에 사용된다. 이러한 모형은 인구통계학적정보, 질병력 및 치료력과 같은 환자 특성들을 조합하여 이를 기반으로 진단 또는 예후 결과를 예측한다.   </p>
<p>임상 예측 모형을 설명하는 출판물의 수가 지난 10년 동안 크게 증가했다. 현재 사용되는 대부분의 모형은 소규모 데이터 집합을 사용하여 추정되며, 소규모 환자 특성만 고려한다. 이처럼 소표본이고 그래서 낮아지는 통계학적 검정력으로 인해 데이터 분석가는 엄격한 가정하게 모델링을 수행하게 된다. 제한적인 환자 특성을 가진 데이터 집합의 선택은 현재 알고 있는 전문가의 지식에만 의존해서 강하게 설명되어진다. 이는 환자들이 풍부한 디지털 트레일(digital trail)을 생성하는 현대 의학의 현실과 크게 대조되며, 이는 모든 의료 전문가가 완전히 동화될 수 있는 힘을 훨씬 뛰어 넘는다. 현재, 건강 관리는 EHR(Electronic Health Records)에 저장된 엄청난 양의 환자 개인별 정보를 생성하고 있다. 여기에는 진단, 약물 치료, 실험실 검사 결과와 같은 정형화된 데이터와 임상적 기술(clinical narratives)에 포함된 비정형화된 데이터가 포함되어 있다. 대량의 환자 데이터를 완전한 EHR로부터 얻고 이것을 활용하여도 예측 정확도를 얼마나 얻을 수 있는지는 알 수 없다. </p>
<p>대규모 데이터셋 분석을 위한 머신 러닝의 발전으로 이러한 유형의 데이터에 환자-수준 예측을 적용하는 데 관심이 높아졌다. 그러나 환자-수준 예측을 위한 많은 수의 출판물들은 모형 개발 지침을 따르지 않아 광범위한 외적 타당도를 수행에 실패하거나 또는 독립적인 연구자들이 그 모형을 재현하고 외적 타당도를 검증하기 위해 필요 가능성을 제한하는 모델링 위한 세부사항을 제공하지 않는다. 이것은 모형의 예측 성능을 공정하게 평가하기 어렵게 하고 임상 실무에서 모형이 적절하게 사용될 가능성을 줄인다. 표준화를 개선하기 위해 예측 모형을 개발하고 그리고 보고하는 모범 사례에 대한 지침을 자세히 설명하는 여러 논문이 작성되었다. 예를 들어, 개별 예측 또는 진단(TRIPOD)<a href="#fn50" class="footnoteRef" id="fnref50"><sup>50</sup></a> 선언문에 다변량 예측 모형의 투명한 보고(Transparent Reporting)는 예측 모형 개발 및 타당도 보고에 대한 명확한 권장 사항을 제공하고 투명성과 관련된 일부 우려를 해결한다.  </p>
<p>OHDSI CDM(Common Data Model)을 통해 전례 없는 규모의 데이터에서 균일하고 투명한 분석이 가능하게 되어 대규모의 환자 개별 예측 모델링이 현실화되었다. CDM으로 표준화된 데이터베이스 네트워크가 증가하면서 전 세계적으로 다양한 의료 환경에서 모형의 외적 타당도 검증을 가능하게 한다. 우리는 이것이 치료의 질적 개선을 가장 필요로 하는 환자의 대규모 공동체에 즉시 서비스를 제공 할 수 있는 기회를 제공한다고 믿는다. 이러한 모형은 정확히 맞춤형 의료서비스에 정보를 제공하고 환자 결과를 크게 향상시킬 수 있다고 희망한다.</p>
<p>이 장에서는 환자-수준 예측을 위한 OHDSI의 표준화된 프레임워크 <span class="citation">(Reps et al. <a href="#ref-reps2018">2018</a>)</span>를 설명하고 개발 및 타당도 검증을 위해 확립된 모범 사례를 구현하는 <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> R 패키지에 대해 설명한다. 우리는 환자-수준 예측의 개발과 평가에 필요한 이론을 제공하는 것으로 시작하고 구현된 기계 학습 알고리즘에 대한 높은 수준의 개요를 제공한다. 그런 다음 예측 문제에 대한 예제에 대하여 논의하고 ATLAS 또는 사용자 정의 R 코드를 사용하여 그것의 정의 및 실행에 대한 단계별 지침을 제공한다. 마지막으로 연구 결과의 보급을 위해 Shiny 앱을 사용하는 방법에 대해 논의한다.</p>
<div id="-" class="section level2">
<h2><span class="header-section-number">13.1</span> 예측 문제</h2>
<p>그림 <a href="PatientLevelPrediction.html#fig:figure1">13.1</a>은 우리가 다루는 예측 문제를 보여준다. 위험에 처한 모집단 중에서, 우리는 정의된 특정 시점(t = 0)에서 어떤 환자가 위험에 처한 동안 어떤 결과를 경험할 것인지 예측하는 것을 목표로 한다. 예측은 해당 시점 이전의 관찰 기간에서 환자에 대한 정보만 사용하여 수행된다.</p>
<div class="figure" style="text-align: center"><span id="fig:figure1"></span>
<img src="images/PatientLevelPrediction/Figure1.png" alt="예측 문제" width="100%" />
<p class="caption">
Figure 13.1: 예측 문제
</p>
</div>
<p>표 <a href="PatientLevelPrediction.html#tab:plpDesign">13.1</a>에서 볼 수 있듯이 예측 문제를 밝히려면 표적 코호트(target cohort)의 t = 0, 결과 코호트(outcome cohort)에 의해 예측하고자하는 결과, 그리고 위험에 노출된 시간(time-at-risk)을 정의해야 한다. 표준 예측 질문을 다음과 같이 정의한다:   </p>
<blockquote>
<p><em>[표적 코호트, T]</em>에서, 누가 <em>[위험에 노출된 시간, t]</em> 내에 <em>[결과 코호트, O]</em>가 발생하는가?</p>
</blockquote>
<p>또한 개발하고자하는 모형에 대해 디자인을 선택하고 내적 및 외적 타당도 검증을 수행할 관측 데이터세트를 결정해야한다.</p>
<table>
<caption><span id="tab:plpDesign">Table 13.1: </span> Main design choices in a prediction design.</caption>
<colgroup>
<col width="24%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Choice</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Target cohort</td>
<td align="left">How do we define the cohort of persons for whom we wish to predict?</td>
</tr>
<tr class="even">
<td align="left">Outcome cohort</td>
<td align="left">How do we define the outcome we want to predict?</td>
</tr>
<tr class="odd">
<td align="left">Time-at-risk</td>
<td align="left">In which time window relative to t=0 do we want to make the prediction?</td>
</tr>
<tr class="even">
<td align="left">Model</td>
<td align="left">What algorithms do we want to use, and which potential predictor variables do we include?</td>
</tr>
</tbody>
</table>
<p>이 개념적 프레임워크는 다음과 같은 모든 유형의 예측 문제에 적용된다, 예를 들면:</p>
<ul>
<li>질병 발병 및 진행</li>
<li><strong>구조</strong>: <em>[질병 A]</em>로 새로 진단 된 환자들 중, **[진단 시점 t]* 내에 <em>[또 다른 질병이나 합병증, B*]</em>이 있는 사람은 누구인가?</li>
<li><strong>예제</strong>: 새로 진단 된 심방 세동 환자 중 향후 3 년 동안 허혈성 뇌졸중이 발생하는 사람은 누구인가?</li>
<li>치료 선택</li>
<li><strong>구조</strong>: <em>[치료 1]</em> 또는 <em>[치료 2]</em>로 치료한 <em>[표시된 질병, D]</em> 환자 중 [치료 1]로 치료받은 환자는 무엇인가?</li>
<li><strong>예제</strong>: 와파린 또는 리바록사반을 복용 한 심방 세동 환자 중 어떤 환자가 와파린을 복용하는가? (예: 성향 모형의 경우)</li>
<li>치료 반응</li>
<li><strong>구조</strong>: <em>[치료 1]</em>을 처음 사용하는 사람 중, 누가 <em>[시간대 t]</em>에서 <em>[어떤 효과, E]</em>를 경험했는가?</li>
<li><strong>예제</strong>: 메트포민으로 치료받기 시작한 당뇨병 환자 중 어떤 환자가 3년 동안 메트포민을 유지하는가?</li>
<li>치료 안전</li>
<li><strong>구조</strong>: <em>[치료 1]</em>을 처음 사용하는 사람 중 누가 <em>[시간대 t]</em>에서 <em>[이상 반응 E]</em>를 경험하게 되는가?</li>
<li><strong>예제</strong>: 와파린을 처음 사용하는 사람 중 누가 1년 안에 위장관 출혈이 발생했는가?</li>
<li>치료 준수</li>
<li><strong>구조</strong>: <em>[치료 1]</em>를 처음 사용하는 사람 중 누가 <em>[시간대, t]</em>에서 <em>[준수 지표수치]</em>를 달성하는가?</li>
<li><strong>예제</strong>: 메트포민으로 치료를 시작한 당뇨병 환자 중 어떤 환자가 1년 중 80 % 이상을 복용 순응도를 보이는가?</li>
</ul>
</div>
<div id="-" class="section level2">
<h2><span class="header-section-number">13.2</span> 데이터 추출</h2>
<p>예측 모형을 만들 때 상태에 따라 분류되어진 예제들 기반으로 공변량과 결과 상태 간의 관계를 유추하기 위하여 기계학습과 같은 지도 학습이라는 프로세스를 사용한다. 따라서, 표적 코호트에 있는 사람들의 CDM에서 공변량을 추출하는 방법이 필요하며 그들의 결과 레이블을 얻을 필요가 있다.</p>
<p><strong>공변량</strong> ( “예측변수”, “특징” 또는 “독립 변수”라고도 함) 은 환자의 특성을 묘사한다. 공변량은 연령, 성별, 특정 질병 존재, 그리고 환자 기록에 있는 노출 코드 그리고 그 외 여러 가지가 될 수 있다. 공변량은 <a href="https://ohdsi.github.io/FeatureExtraction/">FeatureExtraction</a> 패키지를 사용하여 구성되었고, <a href="Characterization.html#Characterization">11</a>장에 자세히 설명되어져 있다. 예측을 위해 우리는 오직 표적 코호트에 들어오는 날짜기준으로 환자의 이전 또는 그 때의 데이터만 사용할 수 있다. 이 날짜를 인덱스 날짜라고 한다.</p>
<p>또한 위험에 노출된 시간(time-at-risk) 동안 모든 환자의 <strong>결과 상태</strong> (“라벨” 또는 “분류”라고도 함) 를 생성할 필요가 있다. 만약 결과가 위험에 노출된 시간안에 발생하며나 그 결과 상태는 “양성”으로 정의된다.  </p>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.2.1</span> 데이터 추출 예제</h3>
<p>표 <a href="PatientLevelPrediction.html#tab:plpExampleCohorts">13.2</a>는 두 개의 코호트가 있는 COHORT에 대한 예를 보여준다. 코호트 정의 ID 1 인 코호트는 표적 코호트 (예를 들어, “최근 심방 세동 진단을 받은 사람들”) 이고 코호트 정의 ID 2는 결과 코호트 (예를 들어, “뇌졸중”) 이다</p>
<table>
<caption><span id="tab:plpExampleCohorts">Table 13.2: </span> Example COHORT table. For simplicity the COHORT_END_DATE has been omitted.</caption>
<thead>
<tr class="header">
<th align="center">COHORT_DEFINITION_ID</th>
<th align="center">SUBJECT_ID</th>
<th align="center">COHORT_START_DATE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">2000-06-01</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">2</td>
<td align="center">2001-06-01</td>
</tr>
<tr class="odd">
<td align="center">2</td>
<td align="center">2</td>
<td align="center">2001-07-01</td>
</tr>
</tbody>
</table>
<p>표 <a href="PatientLevelPrediction.html#tab:plpExampleConditions">13.3</a>은 CONDITION_OCCURRENCE에 대한 예제이다. 개념(concept) ID <a href="http://athena.ohdsi.org/search-terms/terms/320128">320128</a>은 “본태성 고혈압”을 나타낸다.</p>
<table>
<caption><span id="tab:plpExampleConditions">Table 13.3: </span> Example CONDITION_OCCURRENCE table. For simplicity only three columns are shown.</caption>
<thead>
<tr class="header">
<th align="center">PERSON_ID</th>
<th align="center">CONDITION_CONCEPT_ID</th>
<th align="center">CONDITION_START_DATE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">320128</td>
<td align="center">2000-10-01</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">320128</td>
<td align="center">2001-05-01</td>
</tr>
</tbody>
</table>
<p>이 예제 데이터를 기반으로, 위험에 노출된 시간이 인덱스 날짜 (표적 코호트 시작 날짜) 의 다음 연도라고 가정하고 다음과 같이 공변량 및 결과 상태를 구성할 수 있다. Person ID가 1인 환자 (인덱스 날짜 <em>이후</em>에 발생한 질병) 의 경우 “이전 해의 본태성 고혈압”을 나타내는 공변량은 값 0 (현재 아님) 으로 하고, person ID가 2인 환자는 값 1 (현재 진행) 을 갖는다. 유사하게, 결과 상태는 person ID가 1인 환자 (이 사람은 결과 코호트에 못들어감) 의 경우는 값 0 을 갖고 person ID가 2인 환자 (인덱스 날짜 다음 1 년 내에 결과가 발생하였음) 의 경우에는 값 1을 갖는다.</p>
</div>
<div id="section-13.2.2" class="section level3">
<h3><span class="header-section-number">13.2.2</span> 결측</h3>
<p>관찰 의료 데이터는 데이터 누락 여부를 거의 반영하지 않는다. 이전의 예제에서, 우리는 person ID가 1인 환자가 인덱스 날짜 이전에 본태성 고혈압이 없었음을 관찰했다. 이는 그 당시 본태성 고혈압이 없었거나 기록되지 않았기 때문일 수 있다. 머신 러닝 알고리즘은 두 시나리오를 구분할 수 없고 사용 가능한 데이터 안에서 예측 값을 대략 평가한다는 것을 인지해야한다. </p>
</div>
</div>
<div id="modelFitting" class="section level2">
<h2><span class="header-section-number">13.3</span> 모형 적합</h2>
<p>예측 모형을 적합할 때 상태에 따라 분류된 예제들로부터 공변량과 관찰된 결과 상태 간의 관계를 알려고 노력한다. 만약 수축기 혈압과 이완기 혈압의 두 가지 공변량이 있다고 가정하면 그림 <a href="PatientLevelPrediction.html#fig:decisionBoundary">13.2</a>와 같이 2 차원 공간에서 그림으로 각 환자를 나타낼 수 있다. 이 그림에서 데이터를 나타내는 점의 모양은 환자의 결과 상태 (예를 들어, 뇌졸중) 를 나타낸다.</p>
<p>지도 학습 모형은 두 결과 분류(classes)를 최적으로 분리하는 결정 경계(decision boundaries)를 찾아내려고 노력할 것이다. 다른 지도 학습 기법은 다른 분류 결정 경계로 이어지고 분류 결정 경계의 복잡성에 영향을 줄 수 있는 하이퍼-파라미터(hyper-parameters)가 종종 있다.</p>
<div class="figure" style="text-align: center"><span id="fig:decisionBoundary"></span>
<img src="images/PatientLevelPrediction/decisionBoundary.png" alt="결정 경계." width="80%" />
<p class="caption">
Figure 13.2: 결정 경계.
</p>
</div>
<p>그림 <a href="PatientLevelPrediction.html#fig:decisionBoundary">13.2</a>에서 세 가지 다른 결정 경계를 볼 수 있다. 그 경계들은 새로운 데이터포인트의 결과 상태를 추론하기 위하여 사용되어지기도 한다. 새 데이터 포인트가 음영이 있는 영역에 포함되면 모형은 “결과가 있음”을 예측하고, 그렇지 않으면 “결과가 없음”으로 예측한다. 이상적으로는 결정 경계가 두 분류(class)를 완벽하게 구분해야 한다. 그러나 너무 복잡한 모형은 데이터에 “과적합(overfit)”할 위험이 있다. 이는 보이지 않는 데이터에 대한 모형의 일반화에 부정적인 영향을 줄 수 있다. 예를 들어, 데이터에 레이블이 없거나 잘못 지정된 데이터 포인트를 갖는 잡음(noise)이 포함 된 경우 해당 잡음(noise)에 예측 모형을 적합하고 싶지 않을 것이다. 그러므로 우리는 학습 데이터(training data)를 갖고 완벽하게 판별하지는 않지만 “실제의” 복잡성을 반영하는 결정 경계를 정의하는 것을 선호 할 수 있다. 정규화(regularization)와 같은 기술은 복잡성을 최소화하면서 모형 성능을 최대화하는 것을 목표로 한다.</p>
<p>각각의 지도 학습 알고리즘마다 의사 결정 경계를 학습하는 방법이 다르므로 어떤 알고리즘이 데이터에 가장 적합한 지 간단하지 않다. No Free Lunch 정리에 따르면 모든 예측 문제에서 하나의 알고리즘이 언제나 다른 알고리즘보다 성능이 우수하지는 않다는 것을 알 수 있다. 따라서 환자-수준 예측 모형을 개발할 때 다양한 하이퍼-파라미터 설정으로 여러 개의 지도 학습 알고리즘을 사용하는 것이 좋다.</p>
<p>다음의 알고리즘은 <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> 패키지에서 사용할 수 있다:</p>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.3.1</span> 정규화된 로지스틱 회귀</h3>
<p>LASSO(least absolute shrinkage and selection operator) 로지스틱 회귀는 변수의 선형결합을 알 수 있는 일반화 선형 모형(generalized linear models)에 속하고 그리고 로지스틱 함수는 결국 0과 1 사이값으로 배치구조를 나타낸다. LASSO 정규화는 모형 학습시 모형 복잡도에 따른 비용을 목적 함수(objective function)에 추가한다. 이 비용은 계수들의 선형 결합의 절대 값의 합이다. 모형은 이 비용을 최소화하면서 특징 선택(feature selection)을 자동으로 수행한다. 우리는 대규모 정규화 로지스틱 회귀 분석을 수행하기 위하여 <a href="https://ohdsi.github.io/Cyclops/">Cyclops</a>(Cyclic coordinate descent for logistic, Poisson and survival analysis) 패키지를 사용한다.    </p>
<table>
<caption><span id="tab:lassoParameters">Table 13.4: </span> Hyper-parameters for the regularized logistic regression.</caption>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Description</th>
<th align="left">Typical values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Starting variance</td>
<td align="left">The starting variance of the prior distribution.</td>
<td align="left">0.1</td>
</tr>
</tbody>
</table>
<p>교차 검증에서 표본 외(out-of-sample) 우도(likelihood)를 최대화하여 분산이 최적화되므로 시작 분산은 결과 모형의 성능에 거의 영향을 미치지 않는다. 그러나 시작 분산이 최적 값에서 너무 차이가 나면 모형적합 시간이 길어질 수 있다.   </p>
</div>
<div id="gradient-boosting-machines" class="section level3">
<h3><span class="header-section-number">13.3.2</span> Gradient Boosting Machines</h3>
<p>Gradient boosting machines은 부스팅 앙상블 기법(boosting ensemble technique)이며 프레임워크안에서 다중 의사 결정 나무를 연결시킨다. 부스팅은 의사 결정 나무를 반복적으로 추가하는 것이지만, 다음에 생성될 의사결정나무를 학습할 때 비용 함수(cost function)에서 이전 의사 결정 나무에 의해 잘못 분류된 데이터 포인트에 더 많은 가중치를 추가한다. CRAN에서 제공하는 xgboost R 패키지로 수행된 gradient boosting framework를 효율적으로 구현하는 Extreme Gradient Boosting을 사용한다.  </p>
<table>
<caption><span id="tab:gbmParameters">Table 13.5: </span> Hyper-parameters for gradient boosting machines.</caption>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Description</th>
<th align="left">Typical values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">earlyStopRound</td>
<td align="left">Stopping after rounds without improvement</td>
<td align="left">25</td>
</tr>
<tr class="even">
<td align="left">learningRate</td>
<td align="left">The boosting learn rate</td>
<td align="left">0.005,0.01,0.1</td>
</tr>
<tr class="odd">
<td align="left">maxDepth</td>
<td align="left">Max levels in a tree</td>
<td align="left">4,6,17</td>
</tr>
<tr class="even">
<td align="left">minRows</td>
<td align="left">Min data points in a node</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">ntrees</td>
<td align="left">Number of trees</td>
<td align="left">100,1000</td>
</tr>
</tbody>
</table>
</div>
<div id="random-forest" class="section level3">
<h3><span class="header-section-number">13.3.3</span> Random Forest</h3>
<p>랜덤 포레스트(Random forest)는 다중 의사 결정 나무를 연결하는 배깅 앙상블 기법(bagging ensemble technique)이다. 배깅의 기본 개념은 유사도가 낮은 classfiers들을 사용하여 유사도가 높은 classfier로 결합하여 과적합 가능성을 줄이는 것이다. 랜덤 포레스트(Random forest)는 다중 의사 결정 나무를 학습하여 저장하는 것으로 하지만 각 나무(trees)에서 변수의 하위 집합만 사용하며 변수 하위 집합은 의사결정나무마다 다르다. 우리 패키지는 Python에서 Random Forest의 sklearn 수행을 사용한다.   </p>
<table style="width:54%;">
<caption><span id="tab:randomForestParameters">Table 13.6: </span> Hyper-parameters for random forests.</caption>
<colgroup>
<col width="13%" />
<col width="18%" />
<col width="22%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Description</th>
<th align="left">Typical values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">maxDepth</td>
<td align="left">Max levels in a tree</td>
<td align="left">4,10,17</td>
</tr>
<tr class="even">
<td align="left">mtries</td>
<td align="left">Number of features in each tree</td>
<td align="left">-1 = square root of total features,5,20</td>
</tr>
<tr class="odd">
<td align="left">ntrees</td>
<td align="left">Number of trees</td>
<td align="left">500</td>
</tr>
</tbody>
</table>
</div>
<div id="k---k-nearest-neighbor" class="section level3">
<h3><span class="header-section-number">13.3.4</span> K-최근접 이웃 (K-Nearest neighbor)</h3>
<p>KNN(K-nearest neighbors)은 몇 개의 거리 척도(distance metric)를 사용하여 레이블이 지정되지 않은 새로운 데이터 포인트에 가장 가까운 K 개의 레이블이 있는 데이터 포인트를 찾는 알고리즘이다. 새로운 데이터 포인트의 예측은 K-최근접의 레이블이 된 데이터 포인트의 가장 보편적인 분류이다. 모형에 새 데이터에 대한 예측을 수행하기 위해 레이블이 지정된 데이터가 필요하기 때문에 KNN의 공유 제한이 있으며 데이터 사이트간에 이 데이터를 공유 할 수 없는 경우가 종종 있다. 우리는 대규모 KNN classfier인 OHDSI에서 개발된 <a href="https://github.com/OHDSI/BigKnn">BigKnn</a> 패키지를 포함시켰다. </p>
<table>
<caption><span id="tab:knnParameters">Table 13.7: </span> Hyper-parameters for K-nearest neighbors.</caption>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Description</th>
<th align="left">Typical values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">k</td>
<td align="left">Number of neighbors</td>
<td align="left">1000</td>
</tr>
</tbody>
</table>
</div>
<div id="--naive-bayes" class="section level3">
<h3><span class="header-section-number">13.3.5</span> 나이브 베이즈 (Naive Bayes)</h3>
<p>AdaBoost는 부스팅 앙상블 기법(boosting ensemble technique)이다. 부스팅은 classfier를 반복적으로 추가하여 수행되지만 다음 classfier가 학습될 때 비용 함수에서 이전 classfier에 의해 잘못 분류된 데이터 포인트에 더 많은 가중치를 준다. 우리는 파이썬에 있는 sklearn AdaboostClassifier 구현을 사용한다. </p>
</div>
<div id="adaboost" class="section level3">
<h3><span class="header-section-number">13.3.6</span> AdaBoost</h3>
<p>AdaBoost is a boosting ensemble technique. Boosting works by iteratively adding classifiers but adds more weight to the data-points that are misclassified by prior classifiers in the cost function when training the next classifier. We use the sklearn AdaboostClassifier implementation in Python.  </p>
<table style="width:54%;">
<caption><span id="tab:adaBoostParameters">Table 13.8: </span> Hyper-parameters for AdaBoost.</caption>
<colgroup>
<col width="13%" />
<col width="18%" />
<col width="22%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Description</th>
<th align="left">Typical values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">nEstimators</td>
<td align="left">The maximum number of estimators at which boosting is terminated</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">learningRate</td>
<td align="left">Learning rate shrinks the contribution of each classifier by learning_rate. There is a trade-off between learningRate and nEstimators</td>
<td align="left">1</td>
</tr>
</tbody>
</table>
</div>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.3.7</span> 의사 결정 트리</h3>
<p>의사 결정 나무는 탐욕 접근(greedy approach)방식을 사용하여 선택한 개별 테스트를 사용하여 가변 공간을 분할하는 classifier이다. 이것은 클래스를 분리하는 데 가장 많은 정보를 얻는 파티션을 찾는 것을 목표로 한다. 의사 결정 나무는 많은 수의 파티션(tree depth)을 사용하게 되면 쉽게 과적합 되기 때문에 종종 일부 정규화 (예를 들어, 모형의 복잡성을 제한하는 하이퍼-파라미터의 정리 또는 지정) 가 필요하다. 우리는 파이썬에 있는 sklearn DecisionTreeClassifier 구현을 사용한다.  </p>
<p>Table: (#tab:decisionTreeParameters) Hyper-parameters for decision trees.</p>
<p>| Parameter| Description | Typical values | |:——– |:———– |:————– |<br />
| classWeight | “Balance” or “None” | None | | maxDepth | The maximum depth of the tree | 10 | | minImpuritySplit | Threshold for early stopping in tree growth. A node will split if its impurity is above the threshold, otherwise it is a leaf | 10^-7| | minSamplesLeaf | The minimum number of samples per leaf | 10 | | minSamplesSplit | The minimum samples per split | 2 |</p>
</div>
<div id="multilayer-perceptron" class="section level3">
<h3><span class="header-section-number">13.3.8</span> Multilayer Perceptron</h3>
<p>Multilayer perceptrons은 비선형 함수를 사용하여 입력에 가중치를 부여하는 여러 계층의 노드를 포함하는 신경망이다. 첫 번째 레이어는 입력 레이어(input layer)이고 마지막 레이어는 출력 레이어(output layer)이며 그리고 그 사이에는 히든 레이어(hidden layers)가 있다. 신경망은 일반적으로 역 전파(back-propagation)를 사용하여 학습된다. 즉, 학습 입력(training input)이 네트워크를 통해 앞으로 전달되어 출력을 생성하고, 출력과 결과 상태 사이의 오류가 계산되며,이 오류는 네트워크를 통해 뒤로 전달되어 선형 함수 가중치를 업데이트한다.   </p>
<table>
<caption><span id="tab:mpParameters">Table 13.10: </span> Hyper-parameters for Multilayer Perceptrons.</caption>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Description</th>
<th align="left">Typical values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">alpha</td>
<td align="left">The l2 regularization</td>
<td align="left">0.00001</td>
</tr>
<tr class="even">
<td align="left">size</td>
<td align="left">The number of hidden nodes</td>
<td align="left">4</td>
</tr>
</tbody>
</table>
</div>
<div id="--deep-learning" class="section level3">
<h3><span class="header-section-number">13.3.9</span> 딥 러닝 (Deep Learning)</h3>
<p>Deep net, convolutional neural networks 또는 recurrent neural networks와 같은 딥 러닝(deep learning)은 Multilayer perceptrons과 유사하지만 예측에 유용한 잠재 표현을 학습하는 것을 목표로하는 숨겨진 레이어를 여러 개 가지고 있다. <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> 패키지의 별도의 <a href="https://ohdsi.github.io/PatientLevelPrediction/articles/BuildingDeepLearningModels.html">vignette</a> 이러한 모형과 하이퍼-파라미터에 대해 자세히 기술되어 있다.  </p>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.3.10</span> 다른 알고리즘</h3>
<p>다른 알고리즘도 환자-수준 예측 프레임워크에 추가 될 수 있다. 이것은 이 장의 범위를 벗어난다. 자세한 내용은 <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> 패키지의 <a href="https://ohdsi.github.io/PatientLevelPrediction/articles/AddingCustomAlgorithms.html">“Adding Custom Patient-Level Prediction Algorithms” vignette</a> 에 있다.</p>
</div>
</div>
<div id="--" class="section level2">
<h2><span class="header-section-number">13.4</span> 예측 모형 평가</h2>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.4.1</span> 평가 유형</h3>
<p>모형의 예측과 관측된 결과 상태 간의 일치도(agreement)를 측정하여 예측 모형을 평가할 수 있고 그렇게 하려면, 결과 상태를 알 수 있는 데이터가 필요하다. </p>

<div class="rmdimportant">
평가를 위해서는 모형을 개발하는 데 사용 된 것과 다른 데이터세트를 사용해야한다. 그렇지 않으면 과잉 적합 (<a href="PatientLevelPrediction.html#modelFitting">13.3</a>절 참조)되었거나 새로운 환자에게 잘 맞지않는 모형을 선호하게 되는 위험이 발생할 수 있다.
</div>

<p>우리는 내적타당도와 외적타당도로 구분할 수 있다.</p>
<ul>
<li><strong>내적 타당도</strong>: 동일한 데이터베이스에서 추출 된 다른 데이터세트를 사용하여 모형을 개발하고 평가.</li>
<li><strong>외적 타당도</strong>: 한 데이터베이스에서 모형을 개발하고 다른 데이터베이스에서 평가.  </li>
</ul>
<p>아래는 내적 타당도를 수행하는 두 가지 방법에 대한 소개이다:</p>
<ul>
<li><strong>홀드아웃 세트(holdout set) 접근법</strong>은 레이블이 지정된 데이터를 두 개의 독립된 세트로 나눈 것이다: 검증데이터세트(train set)와 테스트세트(test set). 검증세트(train set)는 모형 학습에 사용되고, 테스트세트(test set)는 모형평가에 사용된다. 환자를 무작위로 검증과 테스트 세트로 나누거나 또는 다음과 같이 선택할 수 있다:
<ul>
<li>날짜를 기반으로 데이터를 분할한다. (시점 타당도) 예를 들어, 특정 날짜 이전의 데이터를 학습시키거나, 그 특정 날짜 이후로는 데이터를 평가하는 것이다. 이것은 모형이 서로 다른 시간대에서도 일반화가 가능한지의 여부를 알 수 있게 해준다.</li>
<li>지리적 위치를 기반으로 데이터를 분할한다. (공간 타당도)  </li>
</ul></li>
<li><strong>교차 검증</strong>은 데이터가 제한적일 때 유용하다. 데이터는 <span class="math inline">\(n\)</span>개의 동일한 크기의 세트로 구분된다. 여기서 <span class="math inline">\(n\)</span>은 미리 정해져야 한다(예를 들어, <span class="math inline">\(n=10\)</span>). 이러한 각 세트에 대해 모형은 해당 세트의 데이터를 제외한 모든 데이터에 대해 학습되며 홀드 아웃 세트에 대한 예측을 생성하는 데 사용된다. 이러한 방식으로 모든 데이터가 한 번 사용되어 모형 작성 알고리즘을 평가한다. 환자 수준 예측 프레임 워크에서 교차 검증을 사용하여 최적의 하이퍼-파라미터를 선택한다.</li>
</ul>
<p>외적 타당도는 다른 데이터베이스, 즉 개발에 사용된 데이터베이스가 아닌 다른 데이터베이스로부터 데이터를 얻어 모형 성능을 평가하는 것을 목표로 한다. 이 모형의 타당성을 확보할 수 있는지에 대한 측정은 학습된 데이터베이스뿐만 아니라 모형에 예측 모형에 적용하기 때문에 중요하다. 다른 데이터베이스는 다른 환자 모집단, 다른 의료 시스템 및 다른 데이터 캡처 프로세스를 말할 것이다. 우리는 대규모 데이터베이스 세트에 대한 예측 모형의 외적 타당도 검증이 임상 실무에서 모형이 수행되고 구현되어지기 위한 중요한 단계라고 생각한다.</p>
</div>
<div id="performance" class="section level3">
<h3><span class="header-section-number">13.4.2</span> 성능 지표</h3>
<div id="-" class="section level4 unnumbered">
<h4>임계값 측정</h4>
<p>예측 모형은 위험에 노출된 시간 동안 관심 결과가 발생할 위험에 해당하는 각 환자에 대해 0과 1 사이의 값을 할당한다. 0 값은 0 % 위험을 의미하고 0.5 값은 50 % 위험을 의미하고 1 값은 100 % 위험을 의미한다. 정확도, 민감도, 특이도, 양성 예측도와 같은 일반적인 측정 지표들은 위험에 처한 시간 동안 환자가 관심 결과를 갖는지 여부를 분류하는 데 사용되는 임계 값을 먼저 지정하여 계산할 수 있다. 예를 들어, 표 <a href="PatientLevelPrediction.html#tab:tabletheorytab">13.11</a>에서 임계 값을 0.5로 설정하면 환자 1, 3, 7 및 10은 예상 위험이 임계 값 0.5보다 크거나 같으므로 관심 결과가 발생할 것으로 예측된다. 다른 모든 환자는 0.5 미만의 예측 위험을 가지고 있으므로 관심 결과는 없을 것으로 예측된다.     </p>
<table style="width:76%;">
<caption><span id="tab:tabletheorytab">Table 13.11: </span> Example of using a threshold on the predicted probability.</caption>
<colgroup>
<col width="13%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Patient ID</th>
<th align="center">Predicted risk</th>
<th align="center">Predicted class at 0.5 threshold</th>
<th align="center">Has outcome during time-at-risk</th>
<th align="center">Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">0.8</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">TP</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">0.1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">0.7</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">FP</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">0.05</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">0.1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">0.9</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">TP</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">0.2</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">FN</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">0.3</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">0.5</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">FP</td>
</tr>
</tbody>
</table>
<p>환자에게 관심 결과가 예측되고 (위험 노출 시간 동안) 관심 결과가 발생했다면이를 진양성(TP)이라고 한다. 환자에게 관심 결과가 있을 것으로 예상되지만 그 결과가 없는 경우라면 이를 거짓 양성(FP)이라고 한다. 환자에게 관심 결과가 없을 것으로 예상되고 실제 결과가 없는 경우 이를 진음성(TN)이라고 한다. 마지막으로, 환자에게 관심 결과가 없을 것으로 예상되지만 결과가 있는 경우 이를 거짓 음성(FN)이라고 한다.   </p>
<p>다음과 같이 임계값-기반 지표를 계산할 수 있다:</p>
<ul>
<li>정확도: <span class="math inline">\((TP+TN)/(TP+TN+FP+FN)\)</span></li>
<li>민감도: <span class="math inline">\(TP/(TP+FN)\)</span></li>
<li>특이도: <span class="math inline">\(TN/(TN+FP)\)</span></li>
<li>양성예측도: <span class="math inline">\(TP/(TP+FP)\)</span></li>
</ul>
<p>임계값을 낮추면 이러한 값이 감소하거나 증가 할 수 있다. classifier의 임계값을 낮추면 반영되는 결과 수가 증가하여 분모가 증가할 수 있다. 임계값이 이전에 너무 높게 설정된 경우, 새로운 결과는 모두 진양성일 수 있으며, 이는 양성예측도를 증가시킨다. 이전 임계값이 맞거나 또는 너무 낮다면 임계값을 더 낮추게 되면 거짓양성이 발생하여 양성예측도가 감소한다. 민감도의 분모는 classifirer 임계값 (<span class="math inline">\(TP+FN\)</span>은 상수) 에 의존하지 않는다. 이는 classifier 임계값을 낮추면 진양성 결과 수를 증가시켜 민감도를 높일 수 있음을 의미한다. 또한 임계값을 낮추면 민감도가 바뀌지 않고 양성예측도가 변할 수 있다.</p>
</div>
<div id="ed8c90ebb384eba0a5" class="section level4 unnumbered">
<h4>판별력</h4>
<p>판별력(discrimination)은 위험에 노출된 시간 동안 관심 결과를 경험할 환자에게 더 높은 위험을 할당하는 능력이다. ROC(Receiver Operating Characteristics) 곡선은 가능한 모든 임계값에 대하여 x축은 1-특이도를 그리고 y축에는 민감도를 나타낸다. ROC곡선은 이 장의 뒷부분에 있는 그림 <a href="PatientLevelPrediction.html#fig:shinyROC">13.17</a>에 나와 있다. AUC(area under the receiver operating characteristic curve)가 0.5이면 위험에 무작위로 할당되는 것을 의미하고 값이 1이면 완벽하게 판별한다는 의미이다. 대부분 출판된 예측 모형의 AUC는 0.6-0.8 사이의 값을 갖고 있다.   </p>
<p>AUC는 위험에 노출된 시간 동안 관심 결과를 경험한 환자와 그렇지 않은 환자간에 예측된 위험 분포가 얼마나 다른지 결정하는 방법을 제공한다. AUC가 높으면 위험 분포가 대부분 분리되지만, 겹치는 부분이 많을 때는 그림 <a href="PatientLevelPrediction.html#fig:figuretheoryroctheory">13.3</a>에서와 같이 AUC가 0.5에 가까워진다.</p>
<div class="figure"><span id="fig:figuretheoryroctheory"></span>
<img src="images/PatientLevelPrediction/theory/roctheory.png" alt="How the ROC plots are linked to discrimination. If the two classes have similar distributions of predicted risk, the ROC will be close to the diagonal, with AUC close to 0.5." width="100%" />
<p class="caption">
Figure 13.3: How the ROC plots are linked to discrimination. If the two classes have similar distributions of predicted risk, the ROC will be close to the diagonal, with AUC close to 0.5.
</p>
</div>
<p>결과가 드물게 발생할 경우, AUC가 높은 값을 갖는 모형이라도 주어진 임계값을 초과하는 모든 양성에 대해 음성이 많을 수 있으므로 (즉, 양성예측도가 낮을 수 있기 때문에) 실용적이지 않을 수 있다. 결과의 심각성과 일부 중재에 대한 비용 (건강 위험/ 금전적) 에 따라, 거짓 양성 비가 높아질 수 있다. 결과가 드물게 발생하는 것이라면 AUPRC(area under the precision-recall curve)라고 알려진 다른 측정법이 권장된다. AUPRC는 x축은 민감도 (재현율이라고도 함) 와 y축은 양성예측도 (정밀도라고도 함) 을 나타내는 곡선하 면적이다.index{area under the precision-recall curve}</p>
</div>
<div id="eca081ed95a9eb8f84" class="section level4 unnumbered">
<h4>적합도</h4>
<p>적합도(calibration)는 모형이 정확한 위험을 적합하는지에 대한 것이다. 예를 들어, 모형에 100명의 환자에게 10 %의 위험이 발생가능성이 있다고 할 경우 10명의 환자가 위험에 노출된 시간 동안 결과를 경험해야 한다. 모형에 100명의 환자에게 80 %의 위험이 발생가능성이 있다면 80명의 환자가 위험에 노출되는 시간 동안 결과를 경험해야 한다. 적합도(calibration)는 일반적으로 예측된 위험에 기초하여 환자를 십분 위로 분할하고 각 그룹에서 평균 예측 위험과 위험에 노출 시간 동안 결과를 경험한 환자의 비율을 계산된다. 그런 다음 10개의 점 (y축에 예측 위험과 x축에 관찰된 위험)을 그리고 x = y에 있는지 확인하여 모형이 잘 보정되었음을 나타낸다. 적합도 그래프는 이 장의 뒷부분에 있는 그림 <a href="PatientLevelPrediction.html#fig:shinyCal">13.18</a>에 나와 있다. 또한 점을 사용하여 절편 (0에 가까워 야 함)과 기울기 (1에 가까워 야 함)를 계산하여 선형 모형으로 적합한다. 기울기가 1보다 크면 모형이 실제 위험보다 높은 위험을 할당하고 있고 기울기가 1보다 작으면 모형이 실제 위험보다 낮은 위험을 나타내는 것이다. 또한 예측된 위험과 관찰된 위험 사이의 비선형 관계를 보다 잘 포착하기 위해 R 패키지에 Smooth Calibration Curves를 수행했다.</p>
</div>
</div>
</div>
<div id="----" class="section level2">
<h2><span class="header-section-number">13.5</span> 환자-수준 예측 연구 설계</h2>
<p>이 섹션에서는 예측 연구를 설계하는 방법을 보여준다. 첫 번째 단계는 예측 문제를 명확하게 정의하는 것이다. 흥미롭게도, 많은 출판된 논문에서 예측 문제가 잘 정의되어 있지 않다. 예를 들어 인덱스 날짜(표적 코호트의 시작)가 어떻게 정의되어 있는지 명확하지 않다. 잘못 정의된 예측 문제는 임상 실무에서의 구현은 물론 다른 사람들에 의한 외적 타당도 검정을 불가능하다. 환자-수준 예측 프레임워크에서 표<a href="PatientLevelPrediction.html#tab:plpDesign">13.1</a>에 정의된 주요 선택 사항을 명시적으로 정의하고 예측 문제의 적절한 선택을 한다. 여기서는 “치료의 안전성”을 보는 유형의 예측 문제를 예로 들어 이 프로세스를 살펴보자.</p>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.5.1</span> 문제 정의</h3>
<p>혈관 부종(Angioedema)은 ACE 억제제의 잘 알려진 부작용이며, ACE 억제제에 대한 레이블에 보고된 혈관 부종의 발생률은 0.1 % ~ 0.7 %의 범위이다. <span class="citation">(Byrd, Adam, and Brown <a href="#ref-byrd_2006">2006</a>)</span> 혈관 부종은 드물지만 생명을 위협하여 호흡 정지 및 사망으로 이어질 수 있기 때문에 이러한 부작용에 대한 환자 모니터링은 중요하다. <span class="citation">(Norman et al. <a href="#ref-norman_2013">2013</a>)</span> 또한, 혈관 부종이 초기에 인식되지 않으면, 원인으로 식별되기 전에 범위가 넓어지고 비싼 정밀검사로 이어질 수 있다. <span class="citation">(Norman et al. <a href="#ref-norman_2013">2013</a>; Thompson and Frable <a href="#ref-thompson_1993">1993</a>)</span> 아프리카 계 미국인 환자들 사이에서 발생한 높은 위험외에 ACE 억제제 관련 혈관 부종의 발생에 대한 알려진 소인은 없다. <span class="citation">(Byrd, Adam, and Brown <a href="#ref-byrd_2006">2006</a>)</span> 대부분의 반응은 초기 요법의 첫 주 또는 한 달 안에, 그리고 종종 초기 복용 후 몇 시간 내에 발생한다 <span class="citation">(Cicardi et al. <a href="#ref-circardi_2004">2004</a>)</span>. 그러나 치료가 시작된 후 몇 년이 걸릴 수도 있다. <span class="citation">(O’Mara and O’Mara <a href="#ref-mara_1996">1996</a>)</span> 위험에 처한 사람들을 구체적으로 식별하는 진단 테스트가 없다. 우리가 위험에 처한 사람들을 식별 할 수 있다면, 예를 들어, 의사는 ACE 억제제를 처방을 중단하고 다른 고혈압 약물을 처방할 수 있다. </p>
<p>관찰 의료 데이터에 환자-수준 예측 프레임워크를 적용하여 다음의 환자-수준 예측 질문에 응용해 보자.</p>
<blockquote>
<p>처음에 ACE억제제로 치료를 시작한 환자들 중, 그 다음해에 혈액 부종을 경험한 환자는 누구인가?</p>
</blockquote>
</div>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.5.2</span> 연구 모집단 정의</h3>
<p>예측 모형을 개발하귀 위한 최종 연구 모집단은 종종 표적 코호트의 하위 집단이다. 예를 들어 관심 결과에 의존하는 기준을 적용하거나 또는 표적 코호트의 부분 모집단(sub-population)의 민감도 분석을 수행하고자 하기 때문이다. 이것을 위하여 우리는 다음의 질문들을 설명해야만 한다:</p>
<ul>
<li><p><em>표적 코호트의 인덱스날짜 이전에 필요한 최소 관찰 시간은 얼마입니까?</em> 이 선택은 학습 데이터에서 사용 가능한 환자 시간에 따라 달라질 수 있지만, 장차 모형을 적용하려는 데이터 소스에서 사용 가능할 것으로 예상되는 시간에 따라 달라질 수도 있다. 최소 관측 시간이 길어질수록 더 많은 기저력 시간(baseline history time)이 특징 추출(feature extraction)에 사용할 수 있는 기저력 시간(baseline history time)이 길어지지만 분석 할 수 있는 환자는 줄어든다. 또한, 단기 또는 look-back 기간을 선택해야하는 임상적 이유가 있을 수 있다. 예제에서는 365일 이전 기록을 look-back 기간 (휴약기, washout period)으로 사용한다.</p></li>
<li><p><em>환자가 표적 코호트에 여러 번 포함될 수 있습니까?</em> 표적 코호트 정의에서, 사람은 서로 다른 시간 간격 동안, 예를 들어 서로 다른 에피소드의 질병이 있거나 의료 제품에 대한 별도의 노출 기간이 있는 경우 그 코호트에 여러 번 포함될 수 있다. 코호트 정의는 환자가 한 번만 들어갈 수 있도록 제한을 적용 할 필요는 없지만 특정 환자-수준 예측 문제와 관련하여 코호트를 첫 번째 적격 에피소드로 제한 할 수 있다. 이 예제에서는 기준이 ACE 억제제의 첫 번째 사용을 기반으로 했기 때문에 표적 코호트에 한 번만 들어갈 수 있다.</p></li>
<li><p><em>이전에 관심 결과를 경험 한 사람이 코호트에 들어가도록 허용합니까?</em> 표적 코호트에 포함되기 전에 관심 결과를 경험 한 사람이 표적 코호트에 들어가도록 허용합니까? 특정 환자-수준 예측 문제에 따라, 결과가 처음 발생하게 되는 것을 예측하고자 할 수 있으며, 이 경우 이전에 결과를 경험한 환자는 처음 발생할 위험이 없으므로 표적 코호트에서 제외되어져야 한다. 다른 상황에서, 유행하는 에피소드를 예측하고자하는 경우가 있을 수 있는데, 이로 인해 사전에 관심 결과를 가진 환자가 분석에 포함될 수 있고 사전 결과 자체가 미래 결과를 예측하기 위한 변수가 될 수 있다. 예측을 위한 예제로, 우리는 이전에 혈관 부종을 가진 사람들을 포함하지 않기도 선택할 것이다.</p></li>
<li><p><em>대상 코호트 시작에 대한 결과를 예측할 기간을 어떻게 정의합니까?</em> 우리는 이 질문에 답하기 위해 두 가지 결정을 내려야 한다. 첫째, 위험에 노출된 시간 기간은 표적 코호트가 시작된 날짜 또는 그 이후에 시작되는가? 나중에 시작하게하자는 주장은 표적 코호트가 시작되기 전에 실제로 발생한 기록에서 늦게 입력된 결과를 모면하고 싶거나 그 결과를 방지하기 위한 중재가 이론적으로 구현될 수 있는 것의 차이를 남기고 싶을 수 있다. 둘째, 표적 코호트 시작일 또는 종료일에 대해 상쇄된 날을 지정함으로써위험에 노출된 시간의 기간 정의해야 한다. 우리의 문제를 위해, 우리는 365일까지 표적 코호트의 시작일부터 하루 뒤부터 위험에 노출된 시간의 기간내에서 예측할 것이다.</p></li>
<li><p><em>위험에 노출된 최소 시간이 필요합니까?</em> 관심 결과를 경험하지 않았지만 위험에 노출된 시간이 끝나기 전에 데이터베이스에 남지 않는 환자를 포함시킬 것인지 결정해야 한다. 이 환자들은 더 이상 관찰하지 않는 동안 결과를 경험할 수도 있다. 예측 문제에 대해, 우리는 이 질문에 “예”로 대답하기로 결정했는데, 그 이유는 최소 위험 시간이 필요하기 때문이다. 또한이 제약 조건이 결과를 경험한 사람에게도 적용되는지 결정해야 한다. 그렇지 않으면 위험에 노출된 총 시간에 관계없이 결과를 가진 모든 사람을 포함시켜야 한다. 예를 들어, 결과가 사망인 경우 전체 위험에 노출된 시간이 완료되기 전에 결과를 가진 사람이 중도절단될 가능성이 있다.</p></li>
</ul>
</div>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.5.3</span> 모형 개발 설정</h3>
<p>예측 모형을 개발하기 위해 학습하고자하는 알고리즘을 결정해야 한다. 우리는 경험적 질문으로 특정 예측 문제에 대한 최상의 알고리즘을 선택하는 것이라고 본다. 즉, 데이터 그 자체를 언급하고 가장 최고의 모형을 찾기 위해 다른 접근법을 시도하는 것을 선호한다. 우리 프레임워크에서는 <a href="PatientLevelPrediction.html#modelFitting">13.3</a>절에 설명된 대로 많은 알고리즘을 구현했으며 그리고 다른 알고리즘을 추가 할 수 있다. 이 예제에서는 작업을 단순하게하기 위해 Gradient Boosting Machines 알고리즘을 선택한다.</p>
<p>또한 모형을 학습하기 위하여 사용할 공변량을 결정해야 한다. 이 예제에서는 성별, 연령, 모든 질병, 의약품 및 의약품 그룹 및 방문 횟수를 추가한다. 우리는 이러한 임상적 사건을 인덱스 날짜 이전과 그 전 해에서 발견할 수 있을 것이다.</p>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.5.4</span> 모형 평가</h3>
<p>마지막으로 모형 평가 방법을 정의해야 한다. 편의상 여기서는 내적 타당도를 선택했다. 학습과 테스트를 위한 데이터세트에서 이것을 나누는 방법과 환자를 이 두 데이터세트로 할당하는 방법을 결정해야 한다. 여기에서는 일반적으로 하는 75 %-25 % 분할을 사용한다. 매우 큰 데이터세트의 경우 학습데이터세트에 더 많은 데이터를 포함해서 사용할 수 있다.</p>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.5.5</span> 연구 요약</h3>
<p>우리 연구를 위하여 완벽하게 정의한 내용을 표 <a href="PatientLevelPrediction.html#tab:plpSummary">13.12</a>에 나타내었다.</p>
<table>
<caption><span id="tab:plpSummary">Table 13.12: </span> Main design choices for our study.</caption>
<colgroup>
<col width="24%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Choice</th>
<th align="left">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Target cohort</td>
<td align="left">Patients who have just started on an ACE inhibitor for the first time. Patients are excluded if they have less than 365 days of prior observation time or have prior angioedema.</td>
</tr>
<tr class="even">
<td align="left">Outcome cohort</td>
<td align="left">Angioedema.</td>
</tr>
<tr class="odd">
<td align="left">Time-at-risk</td>
<td align="left">1 day until 365 days from cohort start. We will require at least 364 days at risk.</td>
</tr>
<tr class="even">
<td align="left">Model</td>
<td align="left">Gradient Boosting Machine with hyper-parameters ntree: 5000, max depth: 4 or 7 or 10 and learning rate: 0.001 or 0.01 or 0.1 or 0.9. Covariates will include gender, age, conditions, drugs, drug groups, and visit count. Data split: 75% train - 25% test, randomly assigned by person.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="implementing-the-study-in-atlas" class="section level2">
<h2><span class="header-section-number">13.6</span> Implementing the Study in ATLAS</h2>
<p>예측 연구를 설계 하기 위한 인터페이스는 ATLAS 메뉴<img src="images/PatientLevelPrediction/predictionButton.png" /> 버튼을 누르면 열 수 있다. 새로운 예측 연구를 만든다. 새로운 예측 연구를 생성하십시오. 연구에 알기 쉬운 이름을 부여해라. 연구 디자인은<img src="images/PopulationLevelEstimation/save.png" />버튼을 클릭하면 언제든지 저장이 가능하다. </p>
<p>예측 디자인 기능에는 4개의 세션이 있다: 예측 문제 설정, 분석 설정, 실행 설정, 학습 설정. 다음은 각 세션에 대한 설명이다.</p>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.6.1</span> 예측 문제 설정</h3>
<p>여기서는 표적 코호트와 결과 코호트를 선택할 수 있다. 표적 코호트와 결과 코호트의 모든 조합에 대해 예측 모형이 개발될 것이다. 예를 들어, 만약 두 개의 표적 모집단와 두 개의 대상 결과들을 지정한다면 네 개의 예측 문제가 지정된다.</p>
<p>표적 코호트를 선택하기 위해서는 ATLAS에 사전에 정의되어야 한다. 예시 코호트가 <a href="Cohorts.html#Cohorts">10</a>장에 있다. 부록은 이 예시에 사용된 대상 (부록 <a href="CohortDefinitions.html#AceInhibitors">B.1</a>) 과 결과 (부록 <a href="CohortDefinitions.html#Angioedema">B.4</a>) 코호트의 전체 정의를 제공한다. 표적 모집단을 코호트에 추가하기 위해서는 “표적 코호트 추가 [Add Target Cohort]” 버튼을 클릭해라. 결과 코호트를 추가하는 것은 “결과코호트 추가 [Add Outcome Cohort]” 버튼을 클릭하면 마찬가지로 작동된다. 완료되면, Dialog는 그림 <a href="PatientLevelPrediction.html#fig:problemSettings">13.4</a>처럼 보일 것이다.</p>
<div class="figure" style="text-align: center"><span id="fig:problemSettings"></span>
<img src="images/PatientLevelPrediction/problemSettings.png" alt="예측 문제 설정." width="100%" />
<p class="caption">
Figure 13.4: 예측 문제 설정.
</p>
</div>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.6.2</span> 분석 설정</h3>
<p>분석 설정은 지도 학습 알고리즘, 공변량 및 모집단 설정을 선택 할 수 있다.</p>
<div id="-" class="section level4 unnumbered">
<h4>모형 설정</h4>
<p>모형 개발을 위해 하나 혹은 더 많은 지도 학습 알고리즘을 선택할 수 있다. 지도 학습 알고리즘을 추가 하기 위해서는 “모형 설정 추가 [Add Model Settings]”버튼을 눌러라. 현재 ATLAS에서 지원되는 모든 모형이 포함된 드롭다운이 나타난다. 드롭 다운 메뉴에 있는 이름을 클릭하여 원하는 연구가 포함된 지도 학습 모형을 선택 할 수 있다. 그러고 나면 지정된 모형의 창을 볼 수 있고, 하이퍼-파라미터 값을 선택 할 수 있다. 여러 값이 제공되는 경우 가능한 모든 값들의 조합으로 교차 검증을 사용하여 최적의 조합을 선택하기 위해 그리드서치(Grid Search)를 시행한다.</p>
<p>여기의 예에서는 점진적 부스팅 머신(Gradient Boosting Machine, GBM)을 선택하고 그림 <a href="PatientLevelPrediction.html#fig:gbmSettings">13.5</a>에 지정된 것처럼 하이퍼-파라미터를 설정한다.</p>
<div class="figure" style="text-align: center"><span id="fig:gbmSettings"></span>
<img src="images/PatientLevelPrediction/gbmSettings.png" alt="점진적 부스팅 머신 설정." width="100%" />
<p class="caption">
Figure 13.5: 점진적 부스팅 머신 설정.
</p>
</div>
</div>
<div id="-" class="section level4 unnumbered">
<h4>공변량 설정</h4>
<p>CDM 포멧에 있는 관찰된 데이터로에서 추출할 수 있는 표준 공변량을 정의했다. 공변량 설정 창에서 포함할 표준 공변량을 선택할 수 있다. 다양한 유형의 공변량을 정의 할 수 있으며 각 모형은 각각의 지정된 공변량 설정과 함께 별도로 생성될 것이다.</p>
<p>연구에서 공변량 설정을 추가하려면, “공변량 설정 추가 [Add Covariate Settings]”을 클릭해라. 그러면 공변량 설정 창이 열린다.</p>
공변량 설정 창의 첫 번째 부분은 제외/포함 옵션이다. 공변량은 일반적으로 모든 개념에 맞게 구성된다. 그러나, 어떤 개념이 표적 코호트 정의와 연결되어 있는 경우와 같이 특정한 개념을 추가/제외 하는 것을 원할 수도 있다. 특정 개념만 포함하려면 ATLAS에서 개념 세트(concept set)을 설정한 다음에 <strong>“환자-수준 예측 모형의 기저 공변량에 어떤 개념을 포함 하시겠습니까? (모든 것을 포함하려면 비워 두십시오)”</strong> 아래 <img src="images/PopulationLevelEstimation/open.png" />를 클릭하여 개념 세트(concept set)을 선택한다. <strong>“하위 개념을 포함된 개념 목록에 추가해야 합니까?”</strong>라는 질문에 “예”라고 답함으로써 모든 하위 개념을 자동적으로 개념 세트(concept set)에 추가할 수 있다. 같은 절차는 **환자 수준 예측 모형의 기저 공변량에 어떤 개념을 제외 하시겠습니까? (모든 것을 포함하려면 비워 두십시오)“** 질문에서 동일한 과정을 반복할 수 있고 선택된 개념에 해당하는 공변량을 제거할 수 있다. 마지막 옵션인 <strong>“쉼표는 구분되어야 하는 공변량 ID의 리스트의 범위를 정한다”</strong>를 사용하면 공변량의 IDs 세트 (개념 IDs가 아닌) 을 쉼표로 구분하여 추가할 수 있다. 이 옵션은 고급(advanced) 사용자에게만 있다. 완료가 되면 포함 및 제외 옵션이 그림 <a href="PatientLevelPrediction.html#fig:covariateSettings1">13.6</a>과 같아야 한다. +
<div class="figure" style="text-align: center"><span id="fig:covariateSettings1"></span>
<img src="images/PatientLevelPrediction/covariateSettings1.png" alt="공변량 포함 및 제외 설정." width="100%" />
<p class="caption">
Figure 13.6: 공변량 포함 및 제외 설정.
</p>
</div>
<p>다음은 non-time bound 변수를 선택할 수 있다.</p>
<ul>
<li>성 [Sex]: 남자 또는 여자 성별을 나타내는 이항 변수</li>
<li>나이 [Age]: 연령에 해당하는 연속 변수</li>
<li>나이 그룹 [Age group]: 5년 단위의 이항 변수 (0-4, 5-9, 10-14, …, 95+)</li>
<li>인종 [Race]: 각 인종의 이항 변수, 1은 환자의인종이 기록됨을 의미하며, 그렇지 않으면 0이다.</li>
<li>민족 [Ethnicity]: 민족에 대한 이항 변수, 1은 환자의 민족이 기록됨을 의미하며, 그렇지 않으면 0이다.</li>
<li>색인 연도 [Index year]: 각 코호트 연도 시작 날짜에 대한 이항변수, 1은 환자 코호트 시작 날짜 연도를 의미하고, 그렇지 않으면 0이다. <strong>미래에 이 모형을 적용하기를 원하기 때문에, 때때로는 색인 연도를 포함하는 것은 합리적이지 않다.</strong></li>
<li>색인 월 [Index month]: 각 코호트 달 시작 날짜에 대한 이항 변수, 1은 환자 코호트 월 시작 날짜를 의미하고, 그렇지 않으면 0이다.</li>
<li>사전 관찰 시간 [Prior observation time]: [예측에 권장되지 않음] 코호트 시작일 이전에 환자가 데이터베이스에 있었던 기간 (일) 에 해당하는 연속 변수</li>
<li>사후 관찰 시간 [Post observation time]: [예측에 권장되지 않음] 코호트 시작일 이후에 환자가 데이터베이스에 있었던 기간 (일) 에 해당하는 연속 변수</li>
<li>시간 코호트 [Time cohort]: 환자가 코호트에 있었던 기간에 해당하는 연속 변수 (코호트 종료일에서 코호트 시작일을 뺀)</li>
<li>색인 연도 및 월 [Index year and month]: [예측에 권장되지 않음] 각 코호트 시작 연월 날짜에 대한 이항변수, 1은 환자 코호트 시작 연월 날짜이고, 그렇지 않으면 0이다.</li>
</ul>
<p>완료가 된다면, 그림 <a href="PatientLevelPrediction.html#fig:covariateSettings2">13.7</a>과 같아야 한다.</p>
<div class="figure" style="text-align: center"><span id="fig:covariateSettings2"></span>
<img src="images/PatientLevelPrediction/covariateSettings2.png" alt="공변량 선택." width="100%" />
<p class="caption">
Figure 13.7: 공변량 선택.
</p>
</div>
<p>표준 공변량은 공변량에 대해 세개의 유동적인 시간 간격을 가능하게 한다:</p>
<ul>
<li>종료일: 코호트 시작 날짜를 기준으로 종료시기와의 간격 [기본값 0]</li>
<li>장기간 [코호트 시작일 이전의 기본값 -365일에서 종료일]</li>
<li>중기간 [코호트 시작일 이전의 기본값 -180일에서 종료일]</li>
<li>단기간 [코호트 시작일 이전의 기본값 -30일에서 종료일]</li>
</ul>
<p>완료가 된다면, 그림 <a href="PatientLevelPrediction.html#fig:covariateSettings3">13.8</a>과 같아야 한다.</p>
<div class="figure" style="text-align: center"><span id="fig:covariateSettings3"></span>
<img src="images/PatientLevelPrediction/covariateSettings3.png" alt="Time bound 공변량." width="100%" />
<p class="caption">
Figure 13.8: Time bound 공변량.
</p>
</div>
<p>다음 옵션은 era 테이블에서 추출한 공변량이다:</p>
<ul>
<li>질병 [Condition]: 선택된 각 질병 개념 ID와 시간 간격으로 공변량을 계산하고 환자가 질병 era 테이블에서 코호트 시작일 이전에 지정된 시간 간격 동안, era가 있는 개념 ID를 갖는 경우 (즉, 시간 간격 동안 상태가 시작 또는 종료되었거나 시간 간격 이전에 시작하고 시간 간격 이후에 종료되거나), 공변량 값은 1이고, 그렇지 않으면 0이다.</li>
<li>질병 그룹 [Condition group]: 선택된 각 질병 개념 ID와 시간 간격으로 공변량을 계산하고 환자가 질병 era 테이블에서 코호트 시작일 이전에 지정된 시간 간격 동안, era가 있는 개념 ID를 <strong>또는 하위 개념 ID(any descendant concept ID)</strong>를 갖는 경우, 공변량 값은 1이고, 그렇지 않으면 0이다.</li>
<li>약물 [Drug]: 선택된 각 약물 개념 ID와 시간 간격으로 공변량을 계산하고 환자가 약물 era 테이블에서 코호트 시작일 이전의 지정된 시간 간격 동안 era가 있는 개념 ID를 가지고 있는 경우 공변량 값은 1이며, 그렇지 않으면 0이다.</li>
<li>약물 그룹 [Drug group]: 선택된 각 약물 개념 ID 및 시간 간격으로 공변량을 계산하고 환자가 약물 era 테이블에서 코호트 시작일 이전의 지정된 시간 간격 동안 기간 동안 개념 ID <strong>또는 하위 개념 ID(any descendant concept ID)</strong>를 가진 경우 공변량 값은 1이며, 그렇지 않으면 0이다.</li>
</ul>
<p>겹치는 시간 간격 설정은 약물 또는 질병 발생대(era)가 코호트 시작 날짜 이전에 시작하고 코호트 시작 날짜 이후에 끝나야 하므로 코호트 시작 날짜와 겹친다. Era start 옵션은 선택한 시간 간격 동안 시작되는 질병 또는 약물 era를 찾는 것으로 제한된다.</p>
<p>완료가 된다면, 그림 <a href="PatientLevelPrediction.html#fig:covariateSettings4">13.9</a>과 같아야 한다.</p>
<div class="figure" style="text-align: center"><span id="fig:covariateSettings4"></span>
<img src="images/PatientLevelPrediction/covariateSettings4.png" alt="Time bound era 공변량." width="100%" />
<p class="caption">
Figure 13.9: Time bound era 공변량.
</p>
</div>
<p>다음 옵션은 다양한 시간 간격에 대한 각 도메인의 개념 ID에 해당하는 공변량을 선택한다.</p>
<ul>
<li>질병 [Condition]: 선택된 각 질병 개념 ID 및 시간 간격으로 공변량을 계산하고 환자가 질병 발생 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 개념 ID를 가지고 있는 경우 공변량 값은 1이며, 그렇지 않으면 0이다.</li>
<li>Condition Primary Inpatient (1차입원환자 질병): 질병_발생 표의 입원환자 설정에서 일차 진단으로 관찰된 질병당 이항 공변량 1개이다.</li>
<li>약물 [Drug]: 선택된 각 약물 개념 ID 및 시간 간격으로 공변량을 계산하고 약물 노출 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 개념 ID를 가지고 있는 경우 공변량 값은 1, 그렇지 않으면 0이다.</li>
<li>수술 [Procedure]: 선택된 각 수술 개념 ID 및 시간 간격으로 공변량을 계산하고 환자의 수술 발생 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 개념 ID를 가지고 있는 경우 공변량 값은 1, 그렇지 않으면 0이다.</li>
<li>측정 [Measurement]: 선택된 각 측정 개념 ID 및 시간 간격으로 공변량을 계산하고 환자가 측정 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 개념 ID를 가지고 있는 경우 공변량 값은 1, 그렇지 않으면 0이다.</li>
<li>측정 값 [Measurement Value]: 선택된 각 측정 개념 ID 값과 시간 간격으로 공변량을 계산하며 환자가 측정 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 개념 ID를 가지고 있는 경우 값은 측정 값, 그렇지 않으면 0이다.</li>
<li>측정 범위 그룹 [Measurement range group]: 측정값이 정상 범위 이하인지 이내인지 또는 그 이상인지를 나타내는 이항 공변량이다.</li>
<li>관찰 [Observation]: 선택된 각 관찰 개념 ID와 시간 간격으로 공변량을 계산하며, 환자가 관찰 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 concept ID를 가지고 있는 경우 공변량 값은 1이며, 그렇지 않으면 0이다.</li>
<li>기기 [Device]: 선택된 각 기기 개념 ID 및 시간 간격으로 공변량을 계산하며 환자가 기기 테이블의 코호트 시작일 이전에 지정된 시간 간격 동안 기록된 개념 ID를 가지고 있는 경우 공변량 값은 1이며, 그렇지 않으면 0이다.</li>
<li>방문 수 [Visit count]: 선택된 각 방문 및 시간 간격으로 공변량을 계산하고 시간 간격 동안 기록된 방문 수를 공변량 값으로 계산한다.</li>
<li>방문 개념 수 [Visit Concept Count]: 선택된 각 방문, 도메인 및 시간 간격으로 공변량을 계산하고 방문 유형 및 시간 간격 동안 기록된 도메인 당 기록의 수를 공변량 값으로 계산한다.</li>
</ul>
<p>중복 카운트 옵션은 도메인과 시간 간격 당 중복되는 개념 IDs의 수를 계산한다.</p>
<p>완료가 된다면, 그림 <a href="PatientLevelPrediction.html#fig:covariateSettings5">13.10</a>과 같아야 한다.</p>
<div class="figure" style="text-align: center"><span id="fig:covariateSettings5"></span>
<img src="images/PatientLevelPrediction/covariateSettings5.png" alt="Time bound 공변량." width="100%" />
<p class="caption">
Figure 13.10: Time bound 공변량.
</p>
</div>
<p>마지막 옵션은 공통적으로 사용된 위험 점수를 공변량으로 포함시킬 것 인지의 여부이다. 완료가 된다면, 위험점수 설정은 그림 <a href="PatientLevelPrediction.html#fig:covariateSettings6">13.11</a>과 같아야한다.</p>
<div class="figure" style="text-align: center"><span id="fig:covariateSettings6"></span>
<img src="images/PatientLevelPrediction/covariateSettings6.png" alt="위험 점수 공변량 설정." width="100%" />
<p class="caption">
Figure 13.11: 위험 점수 공변량 설정.
</p>
</div>
</div>
<div id="-" class="section level4 unnumbered">
<h4>모집단 설정</h4>
<p>모집단 설정은 선정 기준이 표적 모집단에 적용할 수 있는 것이며 위험에 노출된 시간을 정의하는 것이기도 하다. 연구에서 모집단 설정을 추가하기 위해서는 “모집단 설정 추가 [Add Population Settings]” 버튼을 클릭하면 모집단 설정 창이 열린다.</p>
<p>옵션의 첫번째 설정은 위험에 노출된 기간을 사용자가 지정할 수 있게 한다. 관심 결과가 발생하는지 알아보는 시간 간격이다. 만약 환자가 위험에 노출된 기간 동안의 관심 결과가 있다면 그것을 “결과가 있음 [Has outcome]”이라고 분류하고, 그렇지 않으면 “결과가 없음 [No outcome]”으로 분류할 것이다. “<strong>표적 코호트 입력과 관련하여 위험에 노출된 시간의 기간 시작의 정의</strong>” 는 표적 코호트 시작과 끝 일자와 비례하여 위험에 노출된 시간으로 정의한다. 마찬가지로, “<strong>위험에 노출된 시간의 기간 종료 정의</strong>”는 위험에 노출된 시간의 끝으로 정의한다.</p>
<p>“<strong>표적 코호트에 적용되는 최소 휴약기간</strong>” 최소 기준 기간, 환자가 지속적으로 관찰되는 코호트 시작일 이전의 최소 일수를 지정한다. 365일이 기본 값이다. 가장 적은 lookback을 늘이는 것은 환자 (더 오래 관찰해야하므로)를 보다 완벽하게 파악할 수 있지만 최소 관찰 일수가 없는 환자를 필터링해야 할 것이다.</p>
<p>“<strong>위험에 노출된 시간이 없는 대상자를 제거해야 하는가?</strong>”에서 ‘예 [yes]’로 설정되어 있다면, “<strong>최소 위험 시간</strong>”의 값도 필요하다. 이를 통해 추척 기간에 잃은 대상 (즉, 위험에 노출된 기간동안 데이터베이스에서 떠난 경우)을 제거 할 수 있다. 예를 들어, 위험에 노출된 기간이 코호트 시작에서부터 365일까지 하루이면 전체 위험발생기간은 364(365-1)일이다. 만약 전체 기간에서 관찰된 환자가 포함되기 원한다면 최소 위험 시간을 364일이라고 설정한다. 사람들이 처음 100일동안 위험에 노출된 시간이 있는 것이 좋은 것이라면, 최소 위험 시간을 100일로 선택한다. 위험에 노출된 시간의 시작이 코호트 시작으로부터 1일이기 때문에 코호트 시작일로부터 적어도 101일 동안 데이터베이스에 남아있으면 환자가 포함될 것이다. 만약 “위험이 있는 대상자를 제거해야 하는가? [Should subjects without time at risk be removed?]” 에서 ‘아니오 [no]’라고 설정하면, 모든 환자들, 위험에 노출된 시간동안 데이터베이스에서 이탈한 환자들까지도 유지할 것이다.</p>
<p>“<strong>위험 기간 전체에서 관찰되지 않은 결과를 가진 사람들을 포함시키겠습니까?</strong>” 옵션은 이전 옵션과 관련된다. “예 [yes]”라고 설정하면 지정된 최소 시간 동안 관찰되지 않더라도 위험에 노출된 시간 동안 결과가 발생한 사람들은 항상 유지된다.</p>
<p>“<strong>대상자마다 첫 번째 노출만 포함되어야 하는가?</strong>” 옵션은 만약 표적 코호트가 다른 코호트 시작일을 가진 환자를 여러 번 포함되어있을 때 유용하다. “예 [yes]”를 선택하면 분석 시 환자 당 가장 처음의 표적 코호트만 유지될 것이다. 그렇지 않으면 환자는 데이터세트에 여러 번 있을 수 있다.</p>
<p>“<strong>코호트 포함시키기 전 관심 결과가 관찰되어진 환자를 제거하시겠습니까?</strong>”에서 “예 [yes]”로 설정한다면 위험에 노출된 시간 시작일 이전의 결과를 가지고 있는 환자들을 제거할 수 있어서 전에 결과를 경험하지 못한 환자들을 위한 모형이 된다. “아니오”를 선택한다면 환자는 이전에 결과를 가지고 있을 수 있다. 종종, 결과를 미리 얻는 것은 위험시간 동안 결과를 얻는 것에 대해 매우 예측가능하다.</p>
<p>완료가 된다면, 모집단 설정 다이얼로그는 그림 <a href="PatientLevelPrediction.html#fig:populationSettings">13.12</a>와 같다.</p>
<div class="figure" style="text-align: center"><span id="fig:populationSettings"></span>
<img src="images/PatientLevelPrediction/populationSettings.png" alt="모집단 설정." width="100%" />
<p class="caption">
Figure 13.12: 모집단 설정.
</p>
</div>
<p>이제 분석 설정을 끝냈으므로, 전체적인 다이얼로그는 그림 <a href="PatientLevelPrediction.html#fig:analysisSettings">13.13</a>와 같다.</p>
<div class="figure" style="text-align: center"><span id="fig:analysisSettings"></span>
<img src="images/PatientLevelPrediction/analysisSettings.png" alt="분석 설정." width="100%" />
<p class="caption">
Figure 13.13: 분석 설정.
</p>
</div>
</div>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.6.3</span> 실행 설정</h3>
<p>여기에는 세가지의 옵션이 있다:</p>
<ul>
<li>“<strong>표본추출 실행</strong>”: 표본추출을 실행할 지 말지 선택할 수 있다 (기본값 = “아니오 [NO]”). 만약 “예 [yes]”라고 설정하면, 또 다른 옵션이 나타날 것이다: “<strong>몇 명의 환자를 부분집합으로 사용할 것인가?</strong>”. 여기서 표본크기는 결정되어질 수 있다. 표본추출은 대규모 모집단 (예 1000만 환자) 의 모형이 환자의 표본을 가지고 모형을 테스트하고 작성함으로써 예측 가능한지 여부를 결정하는 효율적인 수단이 될 수 있다. 예를 들어, 그 표본에서 AUC가 0.5에 가까우면, 그 모형은 쓸모가 없다.</li>
<li>“<strong>최소 공변량 발생: 만약 어떤 공변량이 이 값보다 작은 표적 모집단의 일부에서 발생하면 제거된다:</strong>” 여기서 최소 공변량 발생을 선택할 수 있다 (기본값 = 0.001). 전체 모집단을 대표하지 않은 드문 사건을 제거하려면 공변량 발생의 최소 임계값이 필요하다.</li>
<li>“<strong>공변량 표준화</strong>”: 여기서 공변량을 표준화 할 것인지 선택할 수 있다 (기본값 = “예 [yse]”). 공변량의 표준화는 보통 LASSO모형의 성공적인 요소로 필요로 한다.</li>
</ul>
<p>예를 들어, 그림 <a href="PatientLevelPrediction.html#fig:executionSettings">13.14</a>에 나타난 선택을 한다.</p>
<div class="figure" style="text-align: center"><span id="fig:executionSettings"></span>
<img src="images/PatientLevelPrediction/executionSettings.png" alt="실행 설정." width="100%" />
<p class="caption">
Figure 13.14: 실행 설정.
</p>
</div>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.6.4</span> 학습 설정</h3>
<p>여기에는 네 가지 옵션이 있다:</p>
<ul>
<li>“<strong>테스트/검증 세트를 분할하는 방법 지정:</strong>” 학습/테스트 데이터를 사람 (관심 결과에 따라 분류됨) 별로 구분할지, 시간 (모형을 학습하기 위해 이전 데이터, 나중에 모형을 평가하기 위한 이전 데이터) 별로 구분할지를 선택한다.</li>
<li>“<strong>테스트 세트로 사용될 데이터의 백분율 (0-100%)</strong>”: 테스트 데이터에서 사용될 데이터의 백분율을 선택한다 (기본값 = 25%).</li>
<li>“<strong>교차 검정에 사용된 폴드 수</strong>”: 최적의 하이퍼-파라미터 선택에 사용되는 교차 검증을 위한 폴드 수를 선택한다 (기본값 = 3).</li>
<li>“<strong>사용자 유형 testSplit 사용 시 테스트/검증 세트를 분할하는데 사용되는 초기값 (선택적)</strong>”: 사용자 유형 testSplit에서 트레인/테스트 세트를 분할하는데 사용되는 임의의 초기값을 선택한다.</li>
</ul>
<p>이 예에서는 그림 <a href="PatientLevelPrediction.html#fig:trainingSettings">13.15</a>와 같이 선택을 한다.</p>
<div class="figure" style="text-align: center"><span id="fig:trainingSettings"></span>
<img src="images/PatientLevelPrediction/trainingSettings.png" alt="학습 설정." width="100%" />
<p class="caption">
Figure 13.15: 학습 설정.
</p>
</div>
</div>
<div id="---" class="section level3">
<h3><span class="header-section-number">13.6.5</span> 연구 가져오기 및 내보내기</h3>
<p>연구를 내보내려면 “유틸리티 [Utilities]” 아래의 “내보내기 [Export]”탭을 클릭해야 한다. ATLAS는 연구를 실행할 때 필요한 연구 이름, 코호트 정의, 선택된 모형, 공변량, 설정과 같은 모든 데이터를 포함하는 파일에 직접 복사하여 붙여 넣을 수 있는 JSON을 생성할 것이다. 연구를 가져오려면 “유틸리티 [Utilities]”아래의 “가져오기 [Import]”탭을 클릭해야 한다. 환자 수준 예측 연구 JSON의 내용을 이 창에 붙여 넣은 다음 다른 탭 버튼 아래에 있는 가져오기 버튼을 클릭해야한다. 이 작업은 해당 연구에 대한 이전 설정을 모두 덮어쓰므로 일반적으로 비어있는 새 연구 디자인을 사용할 때 수행된다는 점을 유의해야 한다.</p>
</div>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.6.6</span> 연구 패키지 다운로드</h3>
<p>“유틸리티 [Utilities]”탭 아래의 “리뷰 &amp; 다운로드 [Review &amp; Download]” 클릭해라. “연구 패키지 다운로드 [Download Study Package]” 부분에서 R의 허용되지않은 모든 문자가 ATLAS에 의해 파일 이름에서 자동으로 제거된다는 점에 유의하여 R 패키지 서술 이름을 입력해야 한다. <img src="images/PatientLevelPrediction/download.png" />를 클릭하여 R 패키지를 로컬 폴더로 다운로드 할 수 있다.</p>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.6.7</span> 연구 실행</h3>
<p>R패키지를 실행하려면 <a href="OhdsiAnalyticsTools.html#installR">8.4.5</a>절에 설명 된대로 R, RStudio, Java가 설치되어 있어야 한다. 또한 다음과 같이 R에 설치할 수 있는 <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> 패키지가 필요하다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;drat&quot;</span>)
drat<span class="op">::</span><span class="kw">addRepo</span>(<span class="st">&quot;OHDSI&quot;</span>)
<span class="kw">install.packages</span>(<span class="st">&quot;PatientLevelPrediction&quot;</span>)</code></pre></div>
<p>머신 러닝 알고리즘의 몇몇은 추가적인 소프트웨어 설치를 요구한다. <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>패키지를 설치하는 방법에 대한 자세한 내용은 <a href="https://ohdsi.github.io/PatientLevelPrediction/articles/InstallationGuide.html">“Patient-Level Prediction Installation Guide” vignette</a>를 참조하면 된다.</p>
<p>연구 R패키지를 사용하려면 R Studio를 이용하는 것을 추천한다. 로컬에서 R Studio를 사용 중인 경우 ATLAS에서 생성한 파일의 압축을 풀고 .Rproj를 두번 누르면 RStudio에서 열린다. R스튜디오 서버에서 RStudio를 실행 중인 경우 파일을 업로드 하고 압축을 푼 다음 <img src="images/PopulationLevelEstimation/upload.png" />을 클릭하여 연구프로젝트를 열면 된다.</p>
<p>일단 R Studio에서 연구프로젝트를 열면 README 파일을 열 수 있고 설명을 따르면 된다. 모든 파일 경로를 시스템의 기존 경로로 변경 해야 한다.</p>
</div>
</div>
<div id="r--" class="section level2">
<h2><span class="header-section-number">13.7</span> R에서의 연구 실행</h2>
<p>ATLAS 사용하여 연구디자인을 실행하는 방법은 R에서 코드를 직접 작성하는 것이다. <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>패키지에서 제공하는 함수를 사용할 수 있다. 패키지는 OMOP CDM으로 변환된 데이터로부터 데이터 추출, 모형 구축 및 모형 평가를 가능하게 한다.</p>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.7.1</span> 코호트 예시화</h3>
<p>우선 표적코호트와 결과 코호트를 만들어야 한다. 코호트 만드는 것은 <a href="Cohorts.html#Cohorts">10</a>장에 설명되어 있다. 부록에선 표적 코호트 (부록 <a href="CohortDefinitions.html#AceInhibitors">B.1</a>)와 결과 코호트 (부록 <a href="CohortDefinitions.html#Angioedema">B.4</a>) 에 대한 전체 정의를 제공한다. 이 예제에서 우리는 ACE 억제제 코호트를 ID 1, 혈관부종 코호트를 ID 2로 가정한다.</p>
</div>
<div id="--1" class="section level3">
<h3><span class="header-section-number">13.7.2</span> 데이터 추출</h3>
<p>우선 R에서 서버를 연결해야 한다. <a href="https://ohdsi.github.io/PatientLevelPrediction/"><code>PatientLevelPrediction</code></a>은 다양한 데이터베이스 관리 시스템(DBMS)에 필요한 구체적인 설정을 위한 <code>createConnectionDetails</code>. Type <code>?createConnectionDetails</code> 라고 불리는 기능을 제공하는 <a href="https://ohdsi.github.io/DatabaseConnector/"><code>DatabaseConnector</code></a> 패키지를 사용한다. 예를 들어 이 코드를 사용하여 PostgreSQL 데이터베이스에 연결할 수 있다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(PatientLevelPrediction)
connDetails &lt;-<span class="st"> </span><span class="kw">createConnectionDetails</span>(<span class="dt">dbms =</span> <span class="st">&quot;postgresql&quot;</span>,
                                       <span class="dt">server =</span> <span class="st">&quot;localhost/ohdsi&quot;</span>,
                                       <span class="dt">user =</span> <span class="st">&quot;joe&quot;</span>,
                                       <span class="dt">password =</span> <span class="st">&quot;supersecret&quot;</span>)

cdmDbSchema &lt;-<span class="st"> &quot;my_cdm_data&quot;</span>
cohortsDbSchema &lt;-<span class="st"> &quot;scratch&quot;</span>
cohortsDbTable &lt;-<span class="st"> &quot;my_cohorts&quot;</span>
cdmVersion &lt;-<span class="st"> &quot;5&quot;</span></code></pre></div>
<p>마지막 4줄은 <code>cdmDbSchema</code>, <code>cohortsDbSchema</code> 및 <code>cohortsDbTable</code> 변수와 CDM 버전을 정의한다. 나중에 이것들을 사용하여 CDM 형식의 데이터 위치, 관심있는 코호트 위치, 사용되는 CDM 버전을 R에 입력한다. Microsoft SQL의 경우 데이터베이스 스키마는 데이터와 스키마 모두 지정해야 한다. 예를 들어 <code>cdmDbSchema &lt;- “my_cdm_data.dbo”</code>이다.</p>
<p>먼저 코호트 항목 수를 세어 코호트 생성이 되었는지 확인하는 것이 좋다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sql &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;SELECT cohort_definition_id, COUNT(*) AS count&quot;</span>,
<span class="st">&quot;FROM @cohortsDbSchema.cohortsDbTable&quot;</span>,
<span class="st">&quot;GROUP BY cohort_definition_id&quot;</span>)
conn &lt;-<span class="st"> </span><span class="kw">connect</span>(connDetails)
<span class="kw">renderTranslateQuerySql</span>(<span class="dt">connection =</span> conn, 
                        <span class="dt">sql =</span> sql,
                        <span class="dt">cohortsDbSchema =</span> cohortsDbSchema,
                        <span class="dt">cohortsDbTable =</span> cohortsDbTable)</code></pre></div>
<pre><code>##   cohort_definition_id  count
## 1                    1 527616
## 2                    2   3201</code></pre>
<p>이제 <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>을 통해 분석에 필요한 모든 데이터를 추출할 수 있다. 공변량은 FeatureExtraction 패키지를 사용하여 추출된다. <a href="https://ohdsi.github.io/FeatureExtraction/"><code>FeatureExtraction</code></a> 패키지에 대한 자세한 내용은 해당 vignettes에서 볼 수 있다. 예제 연구에서는 다음과 같은 설정을 사용하기로 결정하였다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">covariateSettings &lt;-<span class="st"> </span><span class="kw">createCovariateSettings</span>(
<span class="dt">useDemographicsGender =</span> <span class="ot">TRUE</span>,
                          <span class="dt">useDemographicsAge =</span> <span class="ot">TRUE</span>,
                          <span class="dt">useConditionGroupEraLongTerm =</span> <span class="ot">TRUE</span>,
                          <span class="dt">useConditionGroupEraAnyTimePrior =</span> <span class="ot">TRUE</span>,
                          <span class="dt">useDrugGroupEraLongTerm =</span> <span class="ot">TRUE</span>,
                          <span class="dt">useDrugGroupEraAnyTimePrior =</span> <span class="ot">TRUE</span>,
                          <span class="dt">useVisitConceptCountLongTerm =</span> <span class="ot">TRUE</span>,
                          <span class="dt">longTermStartDays =</span> <span class="op">-</span><span class="dv">365</span>,
                          <span class="dt">endDays =</span> <span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<p>데이터를 추출의 마지막 단계는 <code>getPlpData</code>함수를 실행하고 코호트가 저장되는 데이터베이스 스키마, 코호트와 결과를 위한 코호트 정의 ID, 해당 사람이 데이터에 포함되도록 관찰되어야하는 코호트 색인 일자 이전의 최소 일자인 최소 휴약기(washout period)와 같은 연결 세부사항들을 입력하는것 이고 마지막으로 이전에 생성된 공변량 설정을 입력하는 것이다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plpData &lt;-<span class="st"> </span><span class="kw">getPlpData</span>(<span class="dt">connectionDetails =</span> connDetails,
                      <span class="dt">cdmDatabaseSchema =</span> cdmDbSchema,
                      <span class="dt">cohortDatabaseSchema =</span> cohortsDbSchema,
                      <span class="dt">cohortTable =</span> cohortsDbSchema,
                      <span class="dt">cohortId =</span> <span class="dv">1</span>,
                      <span class="dt">covariateSettings =</span> covariateSettings,
                      <span class="dt">outcomeDatabaseSchema =</span> cohortsDbSchema,
                      <span class="dt">outcomeTable =</span> cohortsDbSchema,
                      <span class="dt">outcomeIds =</span> <span class="dv">2</span>,
                      <span class="dt">sampleSize =</span> <span class="dv">10000</span>
)</code></pre></div>
<p>(번역 생략된 부분) There are many additional parameters for the <code>getPlpData</code> function which are all documented in the <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> manual. The resulting <code>plpData</code> object uses the package <code>ff</code> to store information in a way that ensures R does not run out of memory, even when the data are large. (번역 생략된 부분) Creating the <code>plpData</code> object can take considerable computing time, and it is probably a good idea to save it for future sessions. Because <code>plpData</code> uses <code>ff</code>, we cannot use R’s regular save function. Instead, we’ll have to use the <code>savePlpData</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">savePlpData</span>(plpData, <span class="st">&quot;angio_in_ace_data&quot;</span>)</code></pre></div>
<p>(번역 생략된 부분) We can use the <code>loadPlpData()</code> function to load the data in a future session.</p>
</div>
<div id="--" class="section level3">
<h3><span class="header-section-number">13.7.3</span> 추가 포함 기준</h3>
<p>최종 연구 모집단은 이전에 정의된 2개의 코호트에서 추가적인 제약조건을 적용하여 얻어진다. 예를 들어 최소 위험에 노출된 시간을 적용할 수 있으며(<code>requireTimeAtRisk, minTimeAtRisk</code>), 이것이 결과를 가진 환자에게도 적용되는지 여부를 지정할 수 있다(<code>includeAllOutcomes</code>). 또한 여기서 표적 코호트 시작에 관련된 위험 기간(risk window)의 시작과 끝을 지정한다. 예를 들어 위험 코호트가 시작된 후 30일부터 위험 기간으로 시작하고 1년 후 종료하려면 <code>riskWindowStart = 30</code>, <code>riskWindowStart = 365</code>로 설정할 수 있다. 경우에 따라 위험 기간은 코호트 종료일에 시작해야 한다. <code>addExposureToStart = Ture</code>으로 설정하면 코호트 (노출) 시간을 시작일에 추가할 수 있다.</p>
<p>아래의 예에서는 연구를 위해 정의한 모든 설정을 시행한 것이다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">population &lt;-<span class="st"> </span><span class="kw">createStudyPopulation</span>(<span class="dt">plpData =</span> plpData,
                                    <span class="dt">outcomeId =</span> <span class="dv">2</span>,
                                    <span class="dt">washoutPeriod =</span> <span class="dv">364</span>,
                                    <span class="dt">firstExposureOnly =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">removeSubjectsWithPriorOutcome =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">priorOutcomeLookback =</span> <span class="dv">9999</span>,
                                    <span class="dt">riskWindowStart =</span> <span class="dv">1</span>,
                                    <span class="dt">riskWindowEnd =</span> <span class="dv">365</span>,
                                    <span class="dt">addExposureDaysToStart =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">addExposureDaysToEnd =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">minTimeAtRisk =</span> <span class="dv">364</span>,
                                    <span class="dt">requireTimeAtRisk =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">includeAllOutcomes =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">verbosity =</span> <span class="st">&quot;DEBUG&quot;</span>
)</code></pre></div>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.7.4</span> 모형 개발</h3>
<p>알고리즘의 설정 기능에서 사용자는 각 하이퍼-파라미터에 대한 적합한 값의 목록을 지정할 수 있다. 하이퍼-파라미터에서 가능한 모든 조합은 학습 세트에 교차 검증을 사용하는 이른바 그리드서치에 포함된다. 만일 사용자가 어떤 값도 지정하지 않으면 기본값이 사용된다.</p>
<p>예를 들어 점진적 부스팅 머신에 다음 설정을 사용하는 경우: <code>ntrees = c(100,200), maxDepth = 4</code> 그리드서치는 점진적 부스팅 머신 알고리즘을 다른 하이퍼-파라미타의 기본 설정을 더한 <code>ntrees = 100</code>과 <code>maxDepth = 4</code> , 다른 하이퍼-파라미타의 기본 설정을 더한 <code>ntrees = 200</code>과 <code>maxDepth = 4</code>에적용할 것이다. 최고의 교차 검증 실행을 이끄는 하이퍼-파라미터는 마지막 모형으로 선택 될 것이다. 이 문제를 위해 여러 하이퍼-파라미터 값을 가지고 점진적 부스팅 머신을 만들기로 하였다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gbmModel &lt;-<span class="st"> </span><span class="kw">setGradientBoostingMachine</span>(<span class="dt">ntrees =</span> <span class="dv">5000</span>, 
                                       <span class="dt">maxDepth =</span> <span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">10</span>), 
                                       <span class="dt">learnRate =</span> <span class="kw">c</span>(<span class="fl">0.001</span>,<span class="fl">0.01</span>,<span class="fl">0.1</span>,<span class="fl">0.9</span>))</code></pre></div>
<p><code>runPIP</code> 함수는 모형을 훈련시키고 평가하기 위해 모집단, <code>plpData</code> 및 모형 설정을 사용한다. 데이터를 75% ~ 25%로 분할하기 위해 <code>testSplit</code>(사람/시간)과 <code>testFraction</code> 파라미터를 사용하고 환자 수준 예측 파이프라인을 실행 할 수 있다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gbmResults &lt;-<span class="st"> </span><span class="kw">runPlp</span>(<span class="dt">population =</span> population, 
                     <span class="dt">plpData =</span> plpData, 
                     <span class="dt">modelSettings =</span> gbmModel, 
                     <span class="dt">testSplit =</span> <span class="st">&#39;person&#39;</span>,
                     <span class="dt">testFraction =</span> <span class="fl">0.25</span>, 
                     <span class="dt">nfold =</span> <span class="dv">2</span>, 
                     <span class="dt">splitSeed =</span> <span class="dv">1234</span>)</code></pre></div>
<p>패키지 안에 R xgboost패키지를 사용하여 데이터의 75%를 사용하는 점진적 부스팅 머신 모형(gradient boosting machine model)을 맞추고 나머지 25%에 대해 모형을 평가 한다. 결과 데이터 구조는 모형과 성능에 대한 정보가 포함되어 있다.</p>
<p><code>runPIP</code> 함수에는 기본적으로 <code>TRUE</code>로 설정된 <code>plpData</code>, <code>plpResults</code>, <code>plpplots</code>, <code>evaluation</code> 등을 저장할 수 있는 몇가지 파라미터가 있다.</p>
<p>다음을 사용하여 모형을 저장할 수 있다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">savePlpModel</span>(gbmResults<span class="op">$</span>model, <span class="dt">dirPath =</span> <span class="st">&quot;model&quot;</span>)</code></pre></div>
<p>(번역 생략된 부분) We can load the model using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plpModel &lt;-<span class="st"> </span><span class="kw">loadPlpModel</span>(<span class="st">&quot;model&quot;</span>)</code></pre></div>
<p>(번역 생략된 부분) You can also save the full results structure using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">savePlpResult</span>(gbmResults, <span class="dt">location =</span> <span class="st">&quot;gbmResults&quot;</span>)</code></pre></div>
<p>(번역 생략된 부분) To load the full results structure use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gbmResults &lt;-<span class="st"> </span><span class="kw">loadPlpResult</span>(<span class="st">&quot;gbmResults&quot;</span>)</code></pre></div>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.7.5</span> 내부 검증</h3>
<p>연구를 실행하면 <code>runPLP</code>함수는 학습/테스트 세트에서 학습된 모형과 학습/테스트 세트에서 모형의 평가를 해준다. <code>viewPLP(runPLP = gbmResults)</code>를 실행하여 양방향의 결과를 볼 수 있다. 이것은 대화식 그림을 포함하여 프레임워크에 생성한 모든 측정 값을 볼 수 있는 Shiny App을 열 것이다(Shiny Application 섹션의 그림 <a href="PatientLevelPrediction.html#fig:shinySummary">13.16</a>을 참조).</p>
<p>모든 평가 그림을 폴더에 생성하고 저장하려면 다음 코드를 실행하면 된다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plotPlp</span>(gbmResults, <span class="st">&quot;plots&quot;</span>)</code></pre></div>
<p>The plots are described in more detail in Section <a href="PatientLevelPrediction.html#performance">13.4.2</a>.</p>
</div>
<div id="-" class="section level3">
<h3><span class="header-section-number">13.7.6</span> 외부 검증</h3>
<p>항상 외적 타당도를 수행하는 것을 권장한다. 즉 가능한 많은 새로운 데이터에 최종모형을 적용하고 성능을 평가해야 한다. 여기서 이미 두 번째 데이터베이스에서 데이터 추출이 수행되어 <code>newData</code> 폴더에 저장되었다고 가정한다. 이전에 장착된 모형을 <code>model</code> 폴더로부터 로딩한다.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load the trained model</span>
plpModel &lt;-<span class="st"> </span><span class="kw">loadPlpModel</span>(<span class="st">&quot;model&quot;</span>)

<span class="co">#load the new plpData and create the population</span>
plpData &lt;-<span class="st"> </span><span class="kw">loadPlpData</span>(<span class="st">&quot;newData&quot;</span>)

population &lt;-<span class="st"> </span><span class="kw">createStudyPopulation</span>(<span class="dt">plpData =</span> plpData,
                                    <span class="dt">outcomeId =</span> <span class="dv">2</span>,
                                    <span class="dt">washoutPeriod =</span> <span class="dv">364</span>,
                                    <span class="dt">firstExposureOnly =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">removeSubjectsWithPriorOutcome =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">priorOutcomeLookback =</span> <span class="dv">9999</span>,
                                    <span class="dt">riskWindowStart =</span> <span class="dv">1</span>,
                                    <span class="dt">riskWindowEnd =</span> <span class="dv">365</span>,
                                    <span class="dt">addExposureDaysToStart =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">addExposureDaysToEnd =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">minTimeAtRisk =</span> <span class="dv">364</span>,
                                    <span class="dt">requireTimeAtRisk =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">includeAllOutcomes =</span> <span class="ot">TRUE</span>
)

<span class="co"># apply the trained model on the new data</span>
validationResults &lt;-<span class="st"> </span><span class="kw">applyModel</span>(population, plpData, plpModel)</code></pre></div>
<p>또한 필요한 데이터를 추출하는 외부 검증을 보다 쉽게 하기 위해 <code>externalValidatePLP</code> 함수를 제공한다. <code>result &lt;- runPlp(...)</code>을 실행했다고 가정했을 때 모형에 필요한 데이터를 추출하여 새 데이터에 대해 평가할 수 있다. 검증 코호트가 ID 1과2가 있는 테이블 <code>mainschema.dob.cohort</code> 과CMD 데이터가 스키마 <code>cdmschema.dob</code> 라고 가정한다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">valResult &lt;-<span class="st"> </span><span class="kw">externalValidatePlp</span>(
    <span class="dt">plpResult =</span> result, 
    <span class="dt">connectionDetails =</span> connectionDetails,
    <span class="dt">validationSchemaTarget =</span> <span class="st">&#39;mainschema.dob&#39;</span>,
    <span class="dt">validationSchemaOutcome =</span> <span class="st">&#39;mainschema.dob&#39;</span>,
    <span class="dt">validationSchemaCdm =</span> <span class="st">&#39;cdmschema.dbo&#39;</span>,
    <span class="dt">databaseNames =</span> <span class="st">&#39;new database&#39;</span>,
    <span class="dt">validationTableTarget =</span> <span class="st">&#39;cohort&#39;</span>,
    <span class="dt">validationTableOutcome =</span> <span class="st">&#39;cohort&#39;</span>,
    <span class="dt">validationIdTarget =</span> <span class="dv">1</span>,
    <span class="dt">validationIdOutcome =</span> <span class="dv">2</span>
)</code></pre></div>
<p>모형을 검증할 데이터베이스가 여러 개 있는 경우 다음을 실행 할 수 있다:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">valResults &lt;-<span class="st"> </span><span class="kw">externalValidatePlp</span>(
    <span class="dt">plpResult =</span> result, 
    <span class="dt">connectionDetails =</span> connectionDetails,
    <span class="dt">validationSchemaTarget =</span> <span class="kw">list</span>(<span class="st">&#39;mainschema.dob&#39;</span>,
                                <span class="st">&#39;difschema.dob&#39;</span>, 
                                <span class="st">&#39;anotherschema.dob&#39;</span>),
    <span class="dt">validationSchemaOutcome =</span> <span class="kw">list</span>(<span class="st">&#39;mainschema.dob&#39;</span>,
                                 <span class="st">&#39;difschema.dob&#39;</span>, 
                                 <span class="st">&#39;anotherschema.dob&#39;</span>),
    <span class="dt">validationSchemaCdm =</span> <span class="kw">list</span>(<span class="st">&#39;cdms1chema.dbo&#39;</span>,
                             <span class="st">&#39;cdm2schema.dbo&#39;</span>,
                             <span class="st">&#39;cdm3schema.dbo&#39;</span>),
    <span class="dt">databaseNames =</span> <span class="kw">list</span>(<span class="st">&#39;new database 1&#39;</span>,
                       <span class="st">&#39;new database 2&#39;</span>,
                       <span class="st">&#39;new database 3&#39;</span>),
    <span class="dt">validationTableTarget =</span> <span class="kw">list</span>(<span class="st">&#39;cohort1&#39;</span>,
                               <span class="st">&#39;cohort2&#39;</span>,
                               <span class="st">&#39;cohort3&#39;</span>),
    <span class="dt">validationTableOutcome =</span> <span class="kw">list</span>(<span class="st">&#39;cohort1&#39;</span>,
                                <span class="st">&#39;cohort2&#39;</span>,
                                <span class="st">&#39;cohort3&#39;</span>),
    <span class="dt">validationIdTarget =</span> <span class="kw">list</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>),
    <span class="dt">validationIdOutcome =</span> <span class="kw">list</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>)
)</code></pre></div>
</div>
</div>
<div id="results-dissemination" class="section level2">
<h2><span class="header-section-number">13.8</span> Results Dissemination</h2>
<div id="model-performance" class="section level3">
<h3><span class="header-section-number">13.8.1</span> Model Performance</h3>
<p>Exploring the performance of a prediction model is easiest with the <code>viewPlp</code> function. This requires a results object as the input. If developing models in R we can use the result of <code>runPLp</code> as the input. If using the ATLAS-generated study package, then we need to load one of the models (in this example we will load Analysis_1): </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plpResult &lt;-<span class="st"> </span><span class="kw">loadPlpResult</span>(<span class="kw">file.path</span>(outputFolder, 
                                     <span class="st">&#39;Analysis_1&#39;</span>, 
                                     <span class="st">&#39;plpResult&#39;</span>))</code></pre></div>
<p>Here “Analysis_1” corresponds to the analysis we specified earlier.</p>
<p>We can then launch the Shiny app by running:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">viewPlp</span>(plpResult)</code></pre></div>
<p>The Shiny app opens with a summary of the performance metrics on the test and train sets (see Figure <a href="PatientLevelPrediction.html#fig:shinySummary">13.16</a>). The results show that the AUC on the train set was 0.78 and this dropped to 0.74 on the test set. The test set AUC is the more accurate measure. Overall, the model appears to be able to discriminate those who will develop the outcome in new users of ACE inhibitors but it slightly overfit as the performance on the train set is higher than the test set. The ROC plot is presented in Figure <a href="PatientLevelPrediction.html#fig:shinyROC">13.17</a>.</p>
<div class="figure"><span id="fig:shinySummary"></span>
<img src="images/PatientLevelPrediction/shinysummary.png" alt="Summary evaluation statistics in the Shiny app." width="100%" />
<p class="caption">
Figure 13.16: Summary evaluation statistics in the Shiny app.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:shinyROC"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyRoc.png" alt="The ROC plot." width="100%" />
<p class="caption">
Figure 13.17: The ROC plot.
</p>
</div>
<p>The calibration plot in Figure <a href="PatientLevelPrediction.html#fig:shinyCal">13.18</a> shows that generally the observed risk matches the predicted risk as the dots are around the diagonal line. The demographic calibration plot in Figure <a href="PatientLevelPrediction.html#fig:shinyDemo">13.19</a> however shows that the model is not well calibrated for the younger patients, as the curved line (the predicted risk) differs from the red line (the observed risk) for those aged below 40. This may indicate we need to remove the under 40s from the target population (as the observed risk for the younger patients is nearly zero).</p>
<div class="figure" style="text-align: center"><span id="fig:shinyCal"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyCal.png" alt="The calibration of the model" width="100%" />
<p class="caption">
Figure 13.18: The calibration of the model
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:shinyDemo"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyDemo.png" alt="The demographic calibration of the model" width="100%" />
<p class="caption">
Figure 13.19: The demographic calibration of the model
</p>
</div>
<p>Finally, the attrition plot shows the loss of patients from the labelled data based on inclusion/exclusion criteria (see Figure <a href="PatientLevelPrediction.html#fig:shinyAtt">13.20</a>). The plot shows that we lost a large portion of the target population due to them not being observed for the whole time at risk (1 year follow up). Interestingly, not as many patients with the outcome lacked the complete time at risk.</p>
<div class="figure" style="text-align: center"><span id="fig:shinyAtt"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyAtt.png" alt="The attrition plot for the prediction problem" width="100%" />
<p class="caption">
Figure 13.20: The attrition plot for the prediction problem
</p>
</div>
</div>
<div id="comparing-models" class="section level3">
<h3><span class="header-section-number">13.8.2</span> Comparing Models</h3>
<p>The study package as generated by ATLAS allows generating and evaluating many different prediction models for different prediction problems. Therefore, specifically for the output generated by the study package an additional Shiny app has been developed for viewing multiple models. To start this app, run <code>viewMultiplePlp(outputFolder)</code> where <code>outputFolder</code> is the path containing the analysis results as specified when running the <code>execute</code> command (and should for example contain a sub-folder named “Analysis_1”).</p>
<div id="viewing-the-model-summary-and-settings" class="section level4 unnumbered">
<h4>Viewing the Model Summary and Settings</h4>
<p>The interactive Shiny app will start at the summary page as shown in Figure <a href="PatientLevelPrediction.html#fig:multiShinySummary">13.21</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:multiShinySummary"></span>
<img src="images/PatientLevelPrediction/shiny/shinyFilter.png" alt="The shiny summary page containing key hold out set performance metrics for each model trained" width="100%" />
<p class="caption">
Figure 13.21: The shiny summary page containing key hold out set performance metrics for each model trained
</p>
</div>
<p>This summary page table contains:</p>
<ul>
<li>basic information about the model (e.g., database information, classifier type, time-at-risk settings, target population and outcome names)</li>
<li>hold out target population count and incidence of outcome</li>
<li>discrimination metrics: AUC, AUPRC</li>
</ul>
<p>To the left of the table is the filter option, where we can specify the development/validation databases to focus on, the type of model, the time at risk settings of interest and/or the cohorts of interest. For example, to pick the models corresponding to the target population “New users of ACE inhibitors as first line mono-therapy for hypertension”, select this in the <em>Target Cohort</em> option.</p>
<p>To explore a model click on the corresponding row, a selected row will be highlighted. With a row selected, we can now explore the model settings used when developing the model by clicking on the <em>Model Settings</em> tab:</p>
<div class="figure" style="text-align: center"><span id="fig:shinyModel"></span>
<img src="images/PatientLevelPrediction/shiny/shinyModel.png" alt="To view the model settings used when developing the model." width="100%" />
<p class="caption">
Figure 13.22: To view the model settings used when developing the model.
</p>
</div>
<p>Similarly, we can explore the population and covariate settings used to generate the model in the other tabs.</p>
</div>
<div id="viewing-model-performance" class="section level4 unnumbered">
<h4>Viewing Model Performance</h4>
<p>Once a model row has been selected we can also view the model performance. Click on <img src="images/PatientLevelPrediction/performance.png" /> to open the threshold performance summary shown in Figure <a href="PatientLevelPrediction.html#fig:shinyPerformanceSum">13.23</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:shinyPerformanceSum"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceSum.png" alt="The summary performance measures at a set threshold." width="100%" />
<p class="caption">
Figure 13.23: The summary performance measures at a set threshold.
</p>
</div>
<p>This summary view shows the selected prediction question in the standard format, a threshold selector and a dashboard containing key threshold-based metrics such as positive predictive value (PPV), negative predictive value (NPV), sensitivity and specificity (see Section <a href="PatientLevelPrediction.html#performance">13.4.2</a>). In Figure <a href="PatientLevelPrediction.html#fig:shinyPerformanceSum">13.23</a> we see that at a threshold of 0.00482 the sensitivity is 83.4% (83.4% of patients with the outcome in the following year have a risk greater than or equal to 0.00482) and the PPV is 1.2% (1.2% of patients with a risk greater than or equal to 0.00482 have the outcome in the following year). As the incidence of the outcome within the year is 0.741%, identifying patients with a risk greater than or equal to 0.00482 would find a subgroup of patients that have nearly double the risk of the population average risk. We can adjust the threshold using the slider to view the performance at other values.</p>
<p>To look at the overall discrimination of the model click on the “Discrimination” tab to view the ROC plot, precision-recall plot, and distribution plots. The line on the plots corresponds to the selected threshold point. Figure <a href="PatientLevelPrediction.html#fig:shinyPerformanceDisc">13.24</a> show the ROC and precision-recall plots. The ROC plot shows the model was able to discriminate between those who will have the outcome within the year and those who will not. However, the performance looks less impressive when we see the precision-recall plot, as the low incidence of the outcome means there is a high false positive rate.</p>
<div class="figure" style="text-align: center"><span id="fig:shinyPerformanceDisc"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceDisc.png" alt="The ROC and precision-recall plots used to access the overal discrimination ability of the model." width="100%" />
<p class="caption">
Figure 13.24: The ROC and precision-recall plots used to access the overal discrimination ability of the model.
</p>
</div>
<p>Figure <a href="PatientLevelPrediction.html#fig:shinyPerformanceDist">13.25</a> shows the prediction and preference score distributions.</p>
<div class="figure" style="text-align: center"><span id="fig:shinyPerformanceDist"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceDist.png" alt="The predicted risk distribution for those with and without the outcome. The more these overlap the worse the discrimination" width="100%" />
<p class="caption">
Figure 13.25: The predicted risk distribution for those with and without the outcome. The more these overlap the worse the discrimination
</p>
</div>
<p>Finally, we can also inspect the calibration of the model by clicking on the “Calibration” tab. This displays the calibration plot and the demographic calibration shown in Figure <a href="PatientLevelPrediction.html#fig:shinyPerformanceCal">13.26</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:shinyPerformanceCal"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceCal.png" alt="The risk stratified calibration and demographic calibration" width="100%" />
<p class="caption">
Figure 13.26: The risk stratified calibration and demographic calibration
</p>
</div>
<p>We see that the average predicted risk appears to match the observed fraction who experienced the outcome within a year, so the model is well calibrated. Interestingly, the demographic calibration shows that the expected line is higher than the observed line for young patients, so we are predicting a higher risk for young age groups. Conversely, for the patients above 80 the model is predicting a lower risk than the observed risk. This may prompt us to develop separate models for the younger or older patients.</p>
</div>
<div id="viewing-the-model" class="section level4 unnumbered">
<h4>Viewing the Model</h4>
<p>To inspect the final model, select the <img src="images/PatientLevelPrediction/modelButton.png" /> option from the left hand menu. This will open a view containing plots for each variable in the model, shown in Figure <a href="PatientLevelPrediction.html#fig:shinyModelPlots">13.27</a>, and a table summarizing all the candidate covariates, shown in Figure <a href="PatientLevelPrediction.html#fig:shinyModelTable">13.28</a>. The variable plots are separated into binary variables and continuous variables. The x-axis is the prevalence/mean in patients without the outcome and the y-axis is the prevalence/mean in patients with the outcome. Therefore, any variable’s dot falling above the diagonal is more common in patients with the outcome and any variable’s dot falling below the diagonal is less common in patients with the outcome.</p>
<div class="figure" style="text-align: center"><span id="fig:shinyModelPlots"></span>
<img src="images/PatientLevelPrediction/shiny/shinyModelPlots.png" alt="Model summary plots. Each dot corresponds to a variable included in the model." width="100%" />
<p class="caption">
Figure 13.27: Model summary plots. Each dot corresponds to a variable included in the model.
</p>
</div>
<p>The table in Figure <a href="PatientLevelPrediction.html#fig:shinyModelTable">13.28</a> displays the name, value (coefficient if using a general linear model, or variable importance otherwise) for all the candidate covariates, outcome mean (the mean value for those who have the outcome) and non-outcome mean (the mean value for those who do not have the outcome).</p>
<div class="figure" style="text-align: center"><span id="fig:shinyModelTable"></span>
<img src="images/PatientLevelPrediction/shiny/shinyModelTable.png" alt="Model details table." width="100%" />
<p class="caption">
Figure 13.28: Model details table.
</p>
</div>

<div class="rmdimportant">
Predictive models are not causal models, and predictors should not be mistaken for causes. There is no guarantee that modifying any of the variables in Figure <a href="PatientLevelPrediction.html#fig:shinyModelTable">13.28</a> will have an effect on the risk of the outcome.
</div>

</div>
</div>
</div>
<div id="additional-patient-level-prediction-features" class="section level2">
<h2><span class="header-section-number">13.9</span> Additional Patient-Level Prediction Features</h2>
<div id="journal-paper-generation" class="section level3">
<h3><span class="header-section-number">13.9.1</span> Journal Paper Generation</h3>
<p>We have added functionality to automatically generate a word document we can use as start of a journal paper. It contains many of the generated study details and results. If we have performed external validation these results will can be added as well. Optionally, we can add a “Table 1” that contains data on many covariates for the target population. We can create the draft journal paper by running this function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">createPlpJournalDocument</span>(<span class="dt">plpResult =</span> <span class="op">&lt;</span>your plp results<span class="op">&gt;</span>,
             <span class="dt">plpValidation =</span> <span class="op">&lt;</span>your validation results<span class="op">&gt;</span>,
             <span class="dt">plpData =</span> <span class="op">&lt;</span>your plp data<span class="op">&gt;</span>,
             <span class="dt">targetName =</span> <span class="st">&quot;&lt;target population&gt;&quot;</span>,
             <span class="dt">outcomeName =</span> <span class="st">&quot;&lt;outcome&gt;&quot;</span>,
             <span class="dt">table1 =</span> F,
             <span class="dt">connectionDetails =</span> <span class="ot">NULL</span>,
             <span class="dt">includeTrain =</span> <span class="ot">FALSE</span>,
             <span class="dt">includeTest =</span> <span class="ot">TRUE</span>,
             <span class="dt">includePredictionPicture =</span> <span class="ot">TRUE</span>,
             <span class="dt">includeAttritionPlot =</span> <span class="ot">TRUE</span>,
             <span class="dt">outputLocation =</span> <span class="st">&quot;&lt;your location&gt;&quot;</span>)</code></pre></div>
<p>For more details see the help page of the function.</p>
</div>
</div>
<div id="-11" class="section level2">
<h2><span class="header-section-number">13.10</span> 요약</h2>

<div class="rmdsummary">
<ul>
<li><p>Patient-level prediction aims to develop a model that predicts future events using data from the past.</p></li>
<li><p>The selection of the best machine algorithm for model development is an empirical question, i.e. it should be driven by the problem and data at hand.</p></li>
<li><p>The PatientLevelPrediction Package implements best practices for the development and validation of prediction models using data stored in the OMOP-CDM.</p></li>
<li><p>The dissemination of the model and its performance measures is implemented through interactive dashboards.</p></li>
<li>OHDSI’s prediction framework enables large-scale external validation of prediction models which is a pre-requisite for clinical adoption.</li>
</ul>
</div>

</div>
<div id="exercises-2" class="section level2">
<h2><span class="header-section-number">13.11</span> Exercises</h2>
<div id="prerequisites-2" class="section level4 unnumbered">
<h4>Prerequisites</h4>
<p>For these exercises we assume R, R-Studio and Java have been installed as described in Section <a href="OhdsiAnalyticsTools.html#installR">8.4.5</a>. Also required are the <a href="https://ohdsi.github.io/SqlRender/">SqlRender</a>, <a href="https://ohdsi.github.io/DatabaseConnector/">DatabaseConnector</a>, <a href="https://ohdsi.github.io/Eunomia/">Eunomia</a> and <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> packages, which can be installed using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="kw">c</span>(<span class="st">&quot;SqlRender&quot;</span>, <span class="st">&quot;DatabaseConnector&quot;</span>, <span class="st">&quot;devtools&quot;</span>))
devtools<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;ohdsi/Eunomia&quot;</span>, <span class="dt">ref =</span> <span class="st">&quot;v1.0.0&quot;</span>)
devtools<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;ohdsi/PatientLevelPrediction&quot;</span>)</code></pre></div>
<p>The Eunomia package provides a simulated dataset in the CDM that will run inside your local R session. The connection details can be obtained using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">connectionDetails &lt;-<span class="st"> </span>Eunomia<span class="op">::</span><span class="kw">getEunomiaConnectionDetails</span>()</code></pre></div>
<p>The CDM database schema is “main”. These exercises also make use of several cohorts. The <code>createCohorts</code> function in the Eunomia package will create these in the COHORT table:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Eunomia<span class="op">::</span><span class="kw">createCohorts</span>(connectionDetails)</code></pre></div>
</div>
<div id="problem-definition-3" class="section level4 unnumbered">
<h4>Problem Definition</h4>
<blockquote>
<p>In patients that started using NSAIDs for the first time, predict who will develop a gastrointestinal (GI) bleed in the next year.</p>
</blockquote>
<p>The NSAID new-user cohort has COHORT_DEFINITION_ID = 4. The GI bleed cohort has COHORT_DEFINITION_ID = 3.</p>

<div class="exercise">
<p><span id="exr:exercisePlp1" class="exercise"><strong>Exercise 13.1  </strong></span>Using the PatientLevelPrediction R package, define the covariates you want to use for the prediction and extract the PLP data from the CDM. Create the summary of the PLP data.</p>
</div>


<div class="exercise">
<p><span id="exr:exercisePlp2" class="exercise"><strong>Exercise 13.2  </strong></span>Revisit the design choices you have to make to define the final target population and specify these using the <code>createStudyPopulation</code> function. What will the effect of your choices be on the final size of the target population?</p>
</div>


<div class="exercise">
<span id="exr:exercisePlp3" class="exercise"><strong>Exercise 13.3  </strong></span>Build a prediction model using LASSO and evaluate its performance using the Shiny application. How well is your model performing?
</div>

<p>Suggested answers can be found in Appendix <a href="SuggestedAnswers.html#Plpanswers">E.9</a>.</p>

</div>
</div>
</div>



<h3>References</h3>
<div id="refs" class="references">
<div id="ref-byrd_2006">
<p>Byrd, J. B., A. Adam, and N. J. Brown. 2006. “Angiotensin-converting enzyme inhibitor-associated angioedema.” <em>Immunol Allergy Clin North Am</em> 26 (4): 725–37.</p>
</div>
<div id="ref-circardi_2004">
<p>Cicardi, M., L. C. Zingale, L. Bergamaschini, and A. Agostoni. 2004. “Angioedema associated with angiotensin-converting enzyme inhibitor use: outcome after switching to a different treatment.” <em>Arch. Intern. Med.</em> 164 (8): 910–13.</p>
</div>
<div id="ref-norman_2013">
<p>Norman, J. L., W. L. Holmes, W. A. Bell, and S. W. Finks. 2013. “Life-threatening ACE inhibitor-induced angioedema after eleven years on lisinopril.” <em>J Pharm Pract</em> 26 (4): 382–88.</p>
</div>
<div id="ref-mara_1996">
<p>O’Mara, N. B., and E. M. O’Mara. 1996. “Delayed onset of angioedema with angiotensin-converting enzyme inhibitors: case report and review of the literature.” <em>Pharmacotherapy</em> 16 (4): 675–79.</p>
</div>
<div id="ref-reps2018">
<p>Reps, J. M., M. J. Schuemie, M. A. Suchard, P. B. Ryan, and P. R. Rijnbeek. 2018. “Design and implementation of a standardized framework to generate and evaluate patient-level prediction models using observational healthcare data.” <em>Journal of the American Medical Informatics Association</em> 25 (8): 969–75. doi:<a href="https://doi.org/10.1093/jamia/ocy032">10.1093/jamia/ocy032</a>.</p>
</div>
<div id="ref-thompson_1993">
<p>Thompson, T., and M. A. Frable. 1993. “Drug-induced, life-threatening angioedema revisited.” <em>Laryngoscope</em> 103 (1 Pt 1): 10–12.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="50">
<li id="fn50"><p><a href="https://www.equator-network.org/reporting-guidelines/tripod-statement/" class="uri">https://www.equator-network.org/reporting-guidelines/tripod-statement/</a><a href="PatientLevelPrediction.html#fnref50">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="PopulationLevelEstimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="EvidenceQuality.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/OHDSI/TheBookOfOhdsi/edit/master/PatientLevelPrediction.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["TheBookOfOhdsiKorea.pdf", "TheBookOfOhdsiKorea.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
